#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 120
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 2
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  anon_sym_SLASH = 1,
  anon_sym_SPACE = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  sym_id = 5,
  sym_name = 6,
  sym_class_name = 7,
  anon_sym_DOT = 8,
  sym_attribute_name = 9,
  anon_sym_EQ = 10,
  anon_sym_SQUOTE = 11,
  anon_sym_DQUOTE = 12,
  sym__text = 13,
  sym_text_content = 14,
  anon_sym_DASH = 15,
  anon_sym_POUND = 16,
  sym_ruby_expression = 17,
  sym__html_identifier = 18,
  sym__newline = 19,
  sym__indent = 20,
  sym__dedent = 21,
  sym_ruby_attributes = 22,
  sym_source_file = 23,
  sym_tag = 24,
  sym__children = 25,
  sym__children_choice = 26,
  sym_html_attributes = 27,
  sym_attributes = 28,
  sym_comment = 29,
  sym_class = 30,
  sym_attribute = 31,
  sym_quoted_attribute_value = 32,
  sym_ruby_block_output = 33,
  sym_ruby_block_run = 34,
  sym_ruby_interpolation = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_tag_repeat1 = 37,
  aux_sym__children_repeat1 = 38,
  aux_sym_html_attributes_repeat1 = 39,
  aux_sym_comment_repeat1 = 40,
  alias_sym_ruby_code = 41,
  alias_sym_self_close_slash = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH] = "/",
  [anon_sym_SPACE] = " ",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_id] = "id",
  [sym_name] = "name",
  [sym_class_name] = "class_name",
  [anon_sym_DOT] = ".",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_EQ] = "=",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym__text] = "_text",
  [sym_text_content] = "text_content",
  [anon_sym_DASH] = "-",
  [anon_sym_POUND] = "#",
  [sym_ruby_expression] = "ruby_expression",
  [sym__html_identifier] = "attribute_value",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_ruby_attributes] = "ruby_attributes",
  [sym_source_file] = "source_file",
  [sym_tag] = "tag",
  [sym__children] = "_children",
  [sym__children_choice] = "_children_choice",
  [sym_html_attributes] = "html_attributes",
  [sym_attributes] = "attributes",
  [sym_comment] = "comment",
  [sym_class] = "class",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_ruby_block_output] = "ruby_block_output",
  [sym_ruby_block_run] = "ruby_block_run",
  [sym_ruby_interpolation] = "ruby_interpolation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym__children_repeat1] = "_children_repeat1",
  [aux_sym_html_attributes_repeat1] = "html_attributes_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [alias_sym_ruby_code] = "ruby_code",
  [alias_sym_self_close_slash] = "self_close_slash",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_id] = sym_id,
  [sym_name] = sym_name,
  [sym_class_name] = sym_class_name,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__text] = sym__text,
  [sym_text_content] = sym_text_content,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_ruby_expression] = sym_ruby_expression,
  [sym__html_identifier] = sym__html_identifier,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_ruby_attributes] = sym_ruby_attributes,
  [sym_source_file] = sym_source_file,
  [sym_tag] = sym_tag,
  [sym__children] = sym__children,
  [sym__children_choice] = sym__children_choice,
  [sym_html_attributes] = sym_html_attributes,
  [sym_attributes] = sym_attributes,
  [sym_comment] = sym_comment,
  [sym_class] = sym_class,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_ruby_block_output] = sym_ruby_block_output,
  [sym_ruby_block_run] = sym_ruby_block_run,
  [sym_ruby_interpolation] = sym_ruby_interpolation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym__children_repeat1] = aux_sym__children_repeat1,
  [aux_sym_html_attributes_repeat1] = aux_sym_html_attributes_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [alias_sym_ruby_code] = alias_sym_ruby_code,
  [alias_sym_self_close_slash] = alias_sym_self_close_slash,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_class_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_ruby_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__html_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_ruby_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__children] = {
    .visible = false,
    .named = true,
  },
  [sym__children_choice] = {
    .visible = false,
    .named = true,
  },
  [sym_html_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_output] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_run] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__children_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_ruby_code] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_self_close_slash] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_ruby_code,
  },
  [2] = {
    [1] = alias_sym_self_close_slash,
  },
  [3] = {
    [2] = alias_sym_self_close_slash,
  },
  [4] = {
    [3] = alias_sym_self_close_slash,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 9,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 19,
  [24] = 24,
  [25] = 13,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 14,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 16,
  [36] = 36,
  [37] = 37,
  [38] = 15,
  [39] = 17,
  [40] = 40,
  [41] = 41,
  [42] = 20,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 21,
  [48] = 18,
  [49] = 24,
  [50] = 50,
  [51] = 22,
  [52] = 45,
  [53] = 36,
  [54] = 29,
  [55] = 34,
  [56] = 40,
  [57] = 32,
  [58] = 44,
  [59] = 41,
  [60] = 33,
  [61] = 31,
  [62] = 46,
  [63] = 43,
  [64] = 37,
  [65] = 27,
  [66] = 28,
  [67] = 67,
  [68] = 68,
  [69] = 68,
  [70] = 67,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 72,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 76,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 77,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 92,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 95,
  [103] = 99,
  [104] = 104,
  [105] = 94,
  [106] = 106,
  [107] = 107,
  [108] = 96,
  [109] = 109,
  [110] = 97,
  [111] = 101,
  [112] = 112,
  [113] = 100,
  [114] = 98,
  [115] = 115,
  [116] = 104,
  [117] = 112,
  [118] = 109,
  [119] = 119,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 33,
        '#', 44,
        '%', 12,
        '\'', 32,
        '(', 20,
        ')', 21,
        '-', 42,
        '.', 27,
        '/', 17,
        '=', 30,
        '{', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '%') ADVANCE(40);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '=') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '%') ADVANCE(12);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '=') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '=') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '\'') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == ')') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(46);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 14:
      if (eof) ADVANCE(16);
      if (lookahead == '\n') SKIP(14);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '%') ADVANCE(40);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '=') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '\n') SKIP(15);
      if (lookahead == '#') ADVANCE(45);
      if (lookahead == '%') ADVANCE(36);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '=') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_class_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '#') ADVANCE(45);
      if (lookahead == '%') ADVANCE(36);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '%') ADVANCE(40);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '=') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_ruby_expression);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__html_identifier);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 14, .external_lex_state = 2},
  [3] = {.lex_state = 14, .external_lex_state = 2},
  [4] = {.lex_state = 14, .external_lex_state = 2},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 4, .external_lex_state = 3},
  [10] = {.lex_state = 4, .external_lex_state = 3},
  [11] = {.lex_state = 4, .external_lex_state = 3},
  [12] = {.lex_state = 4, .external_lex_state = 3},
  [13] = {.lex_state = 15, .external_lex_state = 2},
  [14] = {.lex_state = 14, .external_lex_state = 4},
  [15] = {.lex_state = 14, .external_lex_state = 4},
  [16] = {.lex_state = 14, .external_lex_state = 4},
  [17] = {.lex_state = 14, .external_lex_state = 4},
  [18] = {.lex_state = 14, .external_lex_state = 4},
  [19] = {.lex_state = 15, .external_lex_state = 2},
  [20] = {.lex_state = 14, .external_lex_state = 4},
  [21] = {.lex_state = 14, .external_lex_state = 4},
  [22] = {.lex_state = 14, .external_lex_state = 4},
  [23] = {.lex_state = 15, .external_lex_state = 2},
  [24] = {.lex_state = 14, .external_lex_state = 5},
  [25] = {.lex_state = 15, .external_lex_state = 2},
  [26] = {.lex_state = 4, .external_lex_state = 3},
  [27] = {.lex_state = 14, .external_lex_state = 2},
  [28] = {.lex_state = 14, .external_lex_state = 2},
  [29] = {.lex_state = 14, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 6},
  [31] = {.lex_state = 14, .external_lex_state = 2},
  [32] = {.lex_state = 14, .external_lex_state = 2},
  [33] = {.lex_state = 14, .external_lex_state = 2},
  [34] = {.lex_state = 14, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 6},
  [36] = {.lex_state = 14, .external_lex_state = 2},
  [37] = {.lex_state = 14, .external_lex_state = 2},
  [38] = {.lex_state = 0, .external_lex_state = 6},
  [39] = {.lex_state = 0, .external_lex_state = 6},
  [40] = {.lex_state = 14, .external_lex_state = 2},
  [41] = {.lex_state = 14, .external_lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 6},
  [43] = {.lex_state = 14, .external_lex_state = 2},
  [44] = {.lex_state = 14, .external_lex_state = 2},
  [45] = {.lex_state = 14, .external_lex_state = 2},
  [46] = {.lex_state = 14, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 6},
  [48] = {.lex_state = 0, .external_lex_state = 6},
  [49] = {.lex_state = 0, .external_lex_state = 7},
  [50] = {.lex_state = 4, .external_lex_state = 3},
  [51] = {.lex_state = 0, .external_lex_state = 6},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 4, .external_lex_state = 7},
  [68] = {.lex_state = 4, .external_lex_state = 7},
  [69] = {.lex_state = 4, .external_lex_state = 7},
  [70] = {.lex_state = 4, .external_lex_state = 7},
  [71] = {.lex_state = 4, .external_lex_state = 7},
  [72] = {.lex_state = 4, .external_lex_state = 7},
  [73] = {.lex_state = 5},
  [74] = {.lex_state = 4, .external_lex_state = 7},
  [75] = {.lex_state = 7},
  [76] = {.lex_state = 4, .external_lex_state = 7},
  [77] = {.lex_state = 4, .external_lex_state = 7},
  [78] = {.lex_state = 4, .external_lex_state = 7},
  [79] = {.lex_state = 4, .external_lex_state = 7},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 4, .external_lex_state = 7},
  [82] = {.lex_state = 7},
  [83] = {.lex_state = 4, .external_lex_state = 7},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 5},
  [87] = {.lex_state = 5},
  [88] = {.lex_state = 5},
  [89] = {.lex_state = 6},
  [90] = {.lex_state = 6},
  [91] = {.lex_state = 7},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 3},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 0, .external_lex_state = 7},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0, .external_lex_state = 7},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 3},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 3},
  [109] = {.lex_state = 2},
  [110] = {.lex_state = 3},
  [111] = {.lex_state = 2},
  [112] = {.lex_state = 3},
  [113] = {.lex_state = 2},
  [114] = {.lex_state = 3},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 3},
  [117] = {.lex_state = 3},
  [118] = {.lex_state = 2},
  [119] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_ruby_expression] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym_ruby_attributes] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(106),
    [sym_tag] = STATE(7),
    [sym_comment] = STATE(7),
    [sym_class] = STATE(11),
    [sym_ruby_block_output] = STATE(7),
    [sym_ruby_block_run] = STATE(7),
    [sym_ruby_interpolation] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(5),
    [sym_id] = ACTIONS(7),
    [sym_name] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DOT,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(27), 1,
      sym_text_content,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(31), 1,
      anon_sym_POUND,
    ACTIONS(33), 1,
      sym__dedent,
    STATE(10), 1,
      sym_class,
    ACTIONS(21), 2,
      sym_id,
      sym_name,
    STATE(4), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [41] = 11,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DOT,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(27), 1,
      sym_text_content,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(31), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      sym__dedent,
    STATE(10), 1,
      sym_class,
    ACTIONS(21), 2,
      sym_id,
      sym_name,
    STATE(4), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [82] = 10,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(51), 1,
      sym_text_content,
    ACTIONS(54), 1,
      anon_sym_DASH,
    ACTIONS(57), 1,
      anon_sym_POUND,
    STATE(10), 1,
      sym_class,
    ACTIONS(37), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(42), 2,
      sym_id,
      sym_name,
    STATE(4), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [121] = 9,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DOT,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(31), 1,
      anon_sym_POUND,
    ACTIONS(60), 1,
      sym_text_content,
    STATE(10), 1,
      sym_class,
    ACTIONS(21), 2,
      sym_id,
      sym_name,
    STATE(2), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [156] = 9,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_DOT,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(31), 1,
      anon_sym_POUND,
    ACTIONS(62), 1,
      sym_text_content,
    STATE(10), 1,
      sym_class,
    ACTIONS(21), 2,
      sym_id,
      sym_name,
    STATE(3), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [191] = 9,
    ACTIONS(5), 1,
      anon_sym_SLASH,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_EQ,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_class,
    ACTIONS(7), 2,
      sym_id,
      sym_name,
    STATE(8), 6,
      sym_tag,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [225] = 9,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      anon_sym_SLASH,
    ACTIONS(74), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      anon_sym_EQ,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(83), 1,
      anon_sym_POUND,
    STATE(11), 1,
      sym_class,
    ACTIONS(71), 2,
      sym_id,
      sym_name,
    STATE(8), 6,
      sym_tag,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [259] = 12,
    ACTIONS(23), 1,
      anon_sym_DOT,
    ACTIONS(86), 1,
      anon_sym_SLASH,
    ACTIONS(88), 1,
      anon_sym_SPACE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(96), 1,
      sym__newline,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    STATE(66), 1,
      sym_ruby_block_output,
    STATE(69), 1,
      sym_attributes,
    STATE(81), 1,
      sym_html_attributes,
    ACTIONS(92), 2,
      sym_id,
      sym_name,
    STATE(26), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [298] = 12,
    ACTIONS(23), 1,
      anon_sym_DOT,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_SPACE,
    ACTIONS(106), 1,
      sym__newline,
    STATE(32), 1,
      sym_ruby_block_output,
    STATE(70), 1,
      sym_attributes,
    STATE(81), 1,
      sym_html_attributes,
    ACTIONS(104), 2,
      sym_id,
      sym_name,
    STATE(12), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [337] = 12,
    ACTIONS(23), 1,
      anon_sym_DOT,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(108), 1,
      anon_sym_SLASH,
    ACTIONS(110), 1,
      anon_sym_SPACE,
    ACTIONS(114), 1,
      sym__newline,
    STATE(57), 1,
      sym_ruby_block_output,
    STATE(67), 1,
      sym_attributes,
    STATE(81), 1,
      sym_html_attributes,
    ACTIONS(112), 2,
      sym_id,
      sym_name,
    STATE(9), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [376] = 12,
    ACTIONS(23), 1,
      anon_sym_DOT,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    ACTIONS(118), 1,
      anon_sym_SPACE,
    ACTIONS(120), 1,
      sym__newline,
    STATE(28), 1,
      sym_ruby_block_output,
    STATE(68), 1,
      sym_attributes,
    STATE(81), 1,
      sym_html_attributes,
    ACTIONS(92), 2,
      sym_id,
      sym_name,
    STATE(26), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [415] = 4,
    ACTIONS(126), 1,
      sym__text,
    STATE(13), 1,
      aux_sym_comment_repeat1,
    ACTIONS(122), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(124), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [436] = 4,
    ACTIONS(133), 1,
      sym__indent,
    STATE(45), 1,
      sym__children,
    ACTIONS(129), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(131), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [457] = 4,
    ACTIONS(133), 1,
      sym__indent,
    STATE(37), 1,
      sym__children,
    ACTIONS(135), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(137), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [478] = 4,
    ACTIONS(133), 1,
      sym__indent,
    STATE(44), 1,
      sym__children,
    ACTIONS(139), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(141), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [499] = 4,
    ACTIONS(133), 1,
      sym__indent,
    STATE(36), 1,
      sym__children,
    ACTIONS(143), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(145), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [520] = 4,
    ACTIONS(133), 1,
      sym__indent,
    STATE(33), 1,
      sym__children,
    ACTIONS(147), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(149), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [541] = 5,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 1,
      sym__text,
    ACTIONS(157), 1,
      sym__dedent,
    STATE(13), 1,
      aux_sym_comment_repeat1,
    ACTIONS(153), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [564] = 4,
    ACTIONS(133), 1,
      sym__indent,
    STATE(28), 1,
      sym__children,
    ACTIONS(159), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(161), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [585] = 4,
    ACTIONS(133), 1,
      sym__indent,
    STATE(31), 1,
      sym__children,
    ACTIONS(163), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(165), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [606] = 3,
    ACTIONS(171), 1,
      sym__indent,
    ACTIONS(167), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(169), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [624] = 5,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 1,
      sym__text,
    ACTIONS(175), 1,
      sym__dedent,
    STATE(25), 1,
      aux_sym_comment_repeat1,
    ACTIONS(153), 7,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_POUND,
  [646] = 3,
    ACTIONS(181), 1,
      sym__newline,
    ACTIONS(177), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(179), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [664] = 4,
    ACTIONS(183), 1,
      sym__text,
    STATE(25), 1,
      aux_sym_comment_repeat1,
    ACTIONS(122), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(124), 7,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_POUND,
  [684] = 5,
    ACTIONS(193), 1,
      anon_sym_DOT,
    ACTIONS(190), 2,
      sym_id,
      sym_name,
    STATE(26), 2,
      sym_class,
      aux_sym_tag_repeat1,
    ACTIONS(186), 3,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_EQ,
    ACTIONS(188), 3,
      sym__newline,
      sym_ruby_attributes,
      anon_sym_SPACE,
  [706] = 2,
    ACTIONS(129), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(131), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [721] = 2,
    ACTIONS(139), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(141), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [736] = 2,
    ACTIONS(196), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(198), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [751] = 4,
    ACTIONS(131), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      sym__indent,
    STATE(52), 1,
      sym__children,
    ACTIONS(129), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [770] = 2,
    ACTIONS(202), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(204), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [785] = 2,
    ACTIONS(159), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(161), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [800] = 2,
    ACTIONS(206), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(208), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [815] = 2,
    ACTIONS(210), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(212), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [830] = 4,
    ACTIONS(141), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      sym__indent,
    STATE(58), 1,
      sym__children,
    ACTIONS(139), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [849] = 2,
    ACTIONS(214), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(216), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [864] = 2,
    ACTIONS(218), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(220), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [879] = 4,
    ACTIONS(137), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      sym__indent,
    STATE(64), 1,
      sym__children,
    ACTIONS(135), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [898] = 4,
    ACTIONS(145), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      sym__indent,
    STATE(53), 1,
      sym__children,
    ACTIONS(143), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [917] = 2,
    ACTIONS(147), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(149), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [932] = 2,
    ACTIONS(222), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(224), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [947] = 4,
    ACTIONS(161), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      sym__indent,
    STATE(66), 1,
      sym__children,
    ACTIONS(159), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [966] = 2,
    ACTIONS(226), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(228), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [981] = 2,
    ACTIONS(163), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(165), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [996] = 2,
    ACTIONS(230), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(232), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1011] = 2,
    ACTIONS(135), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(137), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1026] = 4,
    ACTIONS(165), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      sym__indent,
    STATE(61), 1,
      sym__children,
    ACTIONS(163), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1045] = 4,
    ACTIONS(149), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      sym__indent,
    STATE(60), 1,
      sym__children,
    ACTIONS(147), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1064] = 3,
    ACTIONS(179), 1,
      anon_sym_POUND,
    ACTIONS(234), 1,
      sym__newline,
    ACTIONS(177), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1080] = 2,
    ACTIONS(238), 3,
      sym__newline,
      sym_ruby_attributes,
      anon_sym_SPACE,
    ACTIONS(236), 6,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
  [1094] = 3,
    ACTIONS(169), 1,
      anon_sym_POUND,
    ACTIONS(240), 1,
      sym__indent,
    ACTIONS(167), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1110] = 2,
    ACTIONS(232), 1,
      anon_sym_POUND,
    ACTIONS(230), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1123] = 2,
    ACTIONS(216), 1,
      anon_sym_POUND,
    ACTIONS(214), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1136] = 2,
    ACTIONS(198), 1,
      anon_sym_POUND,
    ACTIONS(196), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1149] = 2,
    ACTIONS(212), 1,
      anon_sym_POUND,
    ACTIONS(210), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1162] = 2,
    ACTIONS(149), 1,
      anon_sym_POUND,
    ACTIONS(147), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1175] = 2,
    ACTIONS(161), 1,
      anon_sym_POUND,
    ACTIONS(159), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1188] = 2,
    ACTIONS(165), 1,
      anon_sym_POUND,
    ACTIONS(163), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1201] = 2,
    ACTIONS(224), 1,
      anon_sym_POUND,
    ACTIONS(222), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1214] = 2,
    ACTIONS(208), 1,
      anon_sym_POUND,
    ACTIONS(206), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1227] = 2,
    ACTIONS(204), 1,
      anon_sym_POUND,
    ACTIONS(202), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1240] = 2,
    ACTIONS(137), 1,
      anon_sym_POUND,
    ACTIONS(135), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1253] = 2,
    ACTIONS(228), 1,
      anon_sym_POUND,
    ACTIONS(226), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1266] = 2,
    ACTIONS(220), 1,
      anon_sym_POUND,
    ACTIONS(218), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1279] = 2,
    ACTIONS(131), 1,
      anon_sym_POUND,
    ACTIONS(129), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1292] = 2,
    ACTIONS(141), 1,
      anon_sym_POUND,
    ACTIONS(139), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1305] = 5,
    ACTIONS(86), 1,
      anon_sym_SLASH,
    ACTIONS(88), 1,
      anon_sym_SPACE,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(96), 1,
      sym__newline,
    STATE(66), 1,
      sym_ruby_block_output,
  [1321] = 5,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(242), 1,
      anon_sym_SLASH,
    ACTIONS(244), 1,
      anon_sym_SPACE,
    ACTIONS(246), 1,
      sym__newline,
    STATE(44), 1,
      sym_ruby_block_output,
  [1337] = 5,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(248), 1,
      anon_sym_SLASH,
    ACTIONS(250), 1,
      anon_sym_SPACE,
    ACTIONS(252), 1,
      sym__newline,
    STATE(58), 1,
      sym_ruby_block_output,
  [1353] = 5,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    ACTIONS(118), 1,
      anon_sym_SPACE,
    ACTIONS(120), 1,
      sym__newline,
    STATE(28), 1,
      sym_ruby_block_output,
  [1369] = 2,
    ACTIONS(254), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(256), 2,
      sym__newline,
      anon_sym_SPACE,
  [1378] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(258), 1,
      anon_sym_SPACE,
    ACTIONS(260), 1,
      sym__newline,
    STATE(62), 1,
      sym_ruby_block_output,
  [1391] = 3,
    ACTIONS(262), 1,
      anon_sym_SPACE,
    ACTIONS(266), 1,
      anon_sym_EQ,
    ACTIONS(264), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1402] = 4,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(268), 1,
      anon_sym_SPACE,
    ACTIONS(270), 1,
      sym__newline,
    STATE(46), 1,
      sym_ruby_block_output,
  [1415] = 4,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    ACTIONS(274), 1,
      sym_attribute_name,
    STATE(80), 1,
      aux_sym_html_attributes_repeat1,
    STATE(87), 1,
      sym_attribute,
  [1428] = 4,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(276), 1,
      anon_sym_SPACE,
    ACTIONS(278), 1,
      sym__newline,
    STATE(40), 1,
      sym_ruby_block_output,
  [1441] = 4,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(280), 1,
      anon_sym_SPACE,
    ACTIONS(282), 1,
      sym__newline,
    STATE(27), 1,
      sym_ruby_block_output,
  [1454] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(284), 1,
      anon_sym_SPACE,
    ACTIONS(286), 1,
      sym__newline,
    STATE(56), 1,
      sym_ruby_block_output,
  [1467] = 2,
    ACTIONS(288), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(290), 2,
      sym__newline,
      anon_sym_SPACE,
  [1476] = 4,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    ACTIONS(294), 1,
      sym_attribute_name,
    STATE(80), 1,
      aux_sym_html_attributes_repeat1,
    STATE(87), 1,
      sym_attribute,
  [1489] = 2,
    ACTIONS(297), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(299), 2,
      sym__newline,
      anon_sym_SPACE,
  [1498] = 4,
    ACTIONS(274), 1,
      sym_attribute_name,
    ACTIONS(301), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_html_attributes_repeat1,
    STATE(87), 1,
      sym_attribute,
  [1511] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(303), 1,
      anon_sym_SPACE,
    ACTIONS(305), 1,
      sym__newline,
    STATE(65), 1,
      sym_ruby_block_output,
  [1524] = 3,
    ACTIONS(307), 1,
      anon_sym_SQUOTE,
    ACTIONS(309), 1,
      anon_sym_DQUOTE,
    STATE(86), 1,
      sym_quoted_attribute_value,
  [1534] = 2,
    ACTIONS(311), 1,
      anon_sym_SPACE,
    ACTIONS(313), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1542] = 2,
    ACTIONS(315), 1,
      anon_sym_SPACE,
    ACTIONS(317), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1550] = 2,
    ACTIONS(319), 1,
      anon_sym_SPACE,
    ACTIONS(321), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1558] = 2,
    ACTIONS(323), 1,
      anon_sym_SPACE,
    ACTIONS(325), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1566] = 2,
    ACTIONS(327), 1,
      anon_sym_SQUOTE,
    ACTIONS(329), 1,
      sym__html_identifier,
  [1573] = 2,
    ACTIONS(327), 1,
      anon_sym_DQUOTE,
    ACTIONS(331), 1,
      sym__html_identifier,
  [1580] = 1,
    ACTIONS(292), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1585] = 2,
    ACTIONS(333), 1,
      sym__text,
    STATE(23), 1,
      aux_sym_comment_repeat1,
  [1592] = 2,
    ACTIONS(335), 1,
      sym__text,
    STATE(19), 1,
      aux_sym_comment_repeat1,
  [1599] = 1,
    ACTIONS(337), 1,
      sym_text_content,
  [1603] = 1,
    ACTIONS(339), 1,
      sym_ruby_expression,
  [1607] = 1,
    ACTIONS(341), 1,
      sym_text_content,
  [1611] = 1,
    ACTIONS(343), 1,
      sym_text_content,
  [1615] = 1,
    ACTIONS(345), 1,
      sym_text_content,
  [1619] = 1,
    ACTIONS(347), 1,
      sym__newline,
  [1623] = 1,
    ACTIONS(349), 1,
      sym__text,
  [1627] = 1,
    ACTIONS(351), 1,
      sym__text,
  [1631] = 1,
    ACTIONS(353), 1,
      sym_ruby_expression,
  [1635] = 1,
    ACTIONS(355), 1,
      sym__newline,
  [1639] = 1,
    ACTIONS(357), 1,
      sym_text_content,
  [1643] = 1,
    ACTIONS(359), 1,
      sym_text_content,
  [1647] = 1,
    ACTIONS(361), 1,
      ts_builtin_sym_end,
  [1651] = 1,
    ACTIONS(363), 1,
      anon_sym_SQUOTE,
  [1655] = 1,
    ACTIONS(365), 1,
      sym_text_content,
  [1659] = 1,
    ACTIONS(367), 1,
      sym__text,
  [1663] = 1,
    ACTIONS(369), 1,
      sym_text_content,
  [1667] = 1,
    ACTIONS(371), 1,
      sym__text,
  [1671] = 1,
    ACTIONS(373), 1,
      sym_text_content,
  [1675] = 1,
    ACTIONS(375), 1,
      sym__text,
  [1679] = 1,
    ACTIONS(377), 1,
      sym_text_content,
  [1683] = 1,
    ACTIONS(363), 1,
      anon_sym_DQUOTE,
  [1687] = 1,
    ACTIONS(379), 1,
      sym_text_content,
  [1691] = 1,
    ACTIONS(381), 1,
      sym_text_content,
  [1695] = 1,
    ACTIONS(383), 1,
      sym__text,
  [1699] = 1,
    ACTIONS(385), 1,
      sym_class_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 121,
  [SMALL_STATE(6)] = 156,
  [SMALL_STATE(7)] = 191,
  [SMALL_STATE(8)] = 225,
  [SMALL_STATE(9)] = 259,
  [SMALL_STATE(10)] = 298,
  [SMALL_STATE(11)] = 337,
  [SMALL_STATE(12)] = 376,
  [SMALL_STATE(13)] = 415,
  [SMALL_STATE(14)] = 436,
  [SMALL_STATE(15)] = 457,
  [SMALL_STATE(16)] = 478,
  [SMALL_STATE(17)] = 499,
  [SMALL_STATE(18)] = 520,
  [SMALL_STATE(19)] = 541,
  [SMALL_STATE(20)] = 564,
  [SMALL_STATE(21)] = 585,
  [SMALL_STATE(22)] = 606,
  [SMALL_STATE(23)] = 624,
  [SMALL_STATE(24)] = 646,
  [SMALL_STATE(25)] = 664,
  [SMALL_STATE(26)] = 684,
  [SMALL_STATE(27)] = 706,
  [SMALL_STATE(28)] = 721,
  [SMALL_STATE(29)] = 736,
  [SMALL_STATE(30)] = 751,
  [SMALL_STATE(31)] = 770,
  [SMALL_STATE(32)] = 785,
  [SMALL_STATE(33)] = 800,
  [SMALL_STATE(34)] = 815,
  [SMALL_STATE(35)] = 830,
  [SMALL_STATE(36)] = 849,
  [SMALL_STATE(37)] = 864,
  [SMALL_STATE(38)] = 879,
  [SMALL_STATE(39)] = 898,
  [SMALL_STATE(40)] = 917,
  [SMALL_STATE(41)] = 932,
  [SMALL_STATE(42)] = 947,
  [SMALL_STATE(43)] = 966,
  [SMALL_STATE(44)] = 981,
  [SMALL_STATE(45)] = 996,
  [SMALL_STATE(46)] = 1011,
  [SMALL_STATE(47)] = 1026,
  [SMALL_STATE(48)] = 1045,
  [SMALL_STATE(49)] = 1064,
  [SMALL_STATE(50)] = 1080,
  [SMALL_STATE(51)] = 1094,
  [SMALL_STATE(52)] = 1110,
  [SMALL_STATE(53)] = 1123,
  [SMALL_STATE(54)] = 1136,
  [SMALL_STATE(55)] = 1149,
  [SMALL_STATE(56)] = 1162,
  [SMALL_STATE(57)] = 1175,
  [SMALL_STATE(58)] = 1188,
  [SMALL_STATE(59)] = 1201,
  [SMALL_STATE(60)] = 1214,
  [SMALL_STATE(61)] = 1227,
  [SMALL_STATE(62)] = 1240,
  [SMALL_STATE(63)] = 1253,
  [SMALL_STATE(64)] = 1266,
  [SMALL_STATE(65)] = 1279,
  [SMALL_STATE(66)] = 1292,
  [SMALL_STATE(67)] = 1305,
  [SMALL_STATE(68)] = 1321,
  [SMALL_STATE(69)] = 1337,
  [SMALL_STATE(70)] = 1353,
  [SMALL_STATE(71)] = 1369,
  [SMALL_STATE(72)] = 1378,
  [SMALL_STATE(73)] = 1391,
  [SMALL_STATE(74)] = 1402,
  [SMALL_STATE(75)] = 1415,
  [SMALL_STATE(76)] = 1428,
  [SMALL_STATE(77)] = 1441,
  [SMALL_STATE(78)] = 1454,
  [SMALL_STATE(79)] = 1467,
  [SMALL_STATE(80)] = 1476,
  [SMALL_STATE(81)] = 1489,
  [SMALL_STATE(82)] = 1498,
  [SMALL_STATE(83)] = 1511,
  [SMALL_STATE(84)] = 1524,
  [SMALL_STATE(85)] = 1534,
  [SMALL_STATE(86)] = 1542,
  [SMALL_STATE(87)] = 1550,
  [SMALL_STATE(88)] = 1558,
  [SMALL_STATE(89)] = 1566,
  [SMALL_STATE(90)] = 1573,
  [SMALL_STATE(91)] = 1580,
  [SMALL_STATE(92)] = 1585,
  [SMALL_STATE(93)] = 1592,
  [SMALL_STATE(94)] = 1599,
  [SMALL_STATE(95)] = 1603,
  [SMALL_STATE(96)] = 1607,
  [SMALL_STATE(97)] = 1611,
  [SMALL_STATE(98)] = 1615,
  [SMALL_STATE(99)] = 1619,
  [SMALL_STATE(100)] = 1623,
  [SMALL_STATE(101)] = 1627,
  [SMALL_STATE(102)] = 1631,
  [SMALL_STATE(103)] = 1635,
  [SMALL_STATE(104)] = 1639,
  [SMALL_STATE(105)] = 1643,
  [SMALL_STATE(106)] = 1647,
  [SMALL_STATE(107)] = 1651,
  [SMALL_STATE(108)] = 1655,
  [SMALL_STATE(109)] = 1659,
  [SMALL_STATE(110)] = 1663,
  [SMALL_STATE(111)] = 1667,
  [SMALL_STATE(112)] = 1671,
  [SMALL_STATE(113)] = 1675,
  [SMALL_STATE(114)] = 1679,
  [SMALL_STATE(115)] = 1683,
  [SMALL_STATE(116)] = 1687,
  [SMALL_STATE(117)] = 1691,
  [SMALL_STATE(118)] = 1695,
  [SMALL_STATE(119)] = 1699,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 4),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 4),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 3, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 3, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 3),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 3),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 5, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 5, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 2, 0, 1),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 2, 0, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [183] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [190] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [193] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 2, 0, 1),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 2, 0, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 3),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 3, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__children, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 4, 0, 1),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 4, 0, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 4),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 4),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 6, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 6, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 2),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 2, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [288] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0),
  [294] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 1, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 1, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 0),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [321] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_html_attributes_repeat1, 1, 0, 0),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [361] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token_ruby_attributes = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token_ruby_attributes] = sym_ruby_attributes,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [2] = {
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [4] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
  },
  [7] = {
    [ts_external_token__newline] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_haml_external_scanner_create(void);
void tree_sitter_haml_external_scanner_destroy(void *);
bool tree_sitter_haml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_haml_external_scanner_serialize(void *, char *);
void tree_sitter_haml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_haml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_haml_external_scanner_create,
      tree_sitter_haml_external_scanner_destroy,
      tree_sitter_haml_external_scanner_scan,
      tree_sitter_haml_external_scanner_serialize,
      tree_sitter_haml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
