#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 114
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 2
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  anon_sym_SLASH = 1,
  anon_sym_SPACE = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  sym_id = 5,
  sym_name = 6,
  sym_class_name = 7,
  anon_sym_DOT = 8,
  sym_attribute_name = 9,
  anon_sym_EQ = 10,
  anon_sym_SQUOTE = 11,
  anon_sym_DQUOTE = 12,
  sym__text = 13,
  sym_text_content = 14,
  anon_sym_DASH = 15,
  anon_sym_POUND = 16,
  sym_ruby_expression = 17,
  sym__html_identifier = 18,
  sym__newline = 19,
  sym__indent = 20,
  sym__dedent = 21,
  sym_ruby_attributes = 22,
  sym_source_file = 23,
  sym_tag = 24,
  sym__children = 25,
  sym__children_choice = 26,
  sym_html_attributes = 27,
  sym_attributes = 28,
  sym_comment = 29,
  sym_class = 30,
  sym_attribute = 31,
  sym_quoted_attribute_value = 32,
  sym_ruby_block_output = 33,
  sym_ruby_block_run = 34,
  sym_ruby_interpolation = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_tag_repeat1 = 37,
  aux_sym__children_repeat1 = 38,
  aux_sym_html_attributes_repeat1 = 39,
  alias_sym_ruby_code = 40,
  alias_sym_self_close_slash = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH] = "/",
  [anon_sym_SPACE] = " ",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_id] = "id",
  [sym_name] = "name",
  [sym_class_name] = "class_name",
  [anon_sym_DOT] = ".",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_EQ] = "=",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym__text] = "_text",
  [sym_text_content] = "text_content",
  [anon_sym_DASH] = "-",
  [anon_sym_POUND] = "#",
  [sym_ruby_expression] = "ruby_expression",
  [sym__html_identifier] = "attribute_value",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_ruby_attributes] = "ruby_attributes",
  [sym_source_file] = "source_file",
  [sym_tag] = "tag",
  [sym__children] = "_children",
  [sym__children_choice] = "_children_choice",
  [sym_html_attributes] = "html_attributes",
  [sym_attributes] = "attributes",
  [sym_comment] = "comment",
  [sym_class] = "class",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_ruby_block_output] = "ruby_block_output",
  [sym_ruby_block_run] = "ruby_block_run",
  [sym_ruby_interpolation] = "ruby_interpolation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym__children_repeat1] = "_children_repeat1",
  [aux_sym_html_attributes_repeat1] = "html_attributes_repeat1",
  [alias_sym_ruby_code] = "ruby_code",
  [alias_sym_self_close_slash] = "self_close_slash",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_id] = sym_id,
  [sym_name] = sym_name,
  [sym_class_name] = sym_class_name,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__text] = sym__text,
  [sym_text_content] = sym_text_content,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_ruby_expression] = sym_ruby_expression,
  [sym__html_identifier] = sym__html_identifier,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_ruby_attributes] = sym_ruby_attributes,
  [sym_source_file] = sym_source_file,
  [sym_tag] = sym_tag,
  [sym__children] = sym__children,
  [sym__children_choice] = sym__children_choice,
  [sym_html_attributes] = sym_html_attributes,
  [sym_attributes] = sym_attributes,
  [sym_comment] = sym_comment,
  [sym_class] = sym_class,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_ruby_block_output] = sym_ruby_block_output,
  [sym_ruby_block_run] = sym_ruby_block_run,
  [sym_ruby_interpolation] = sym_ruby_interpolation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym__children_repeat1] = aux_sym__children_repeat1,
  [aux_sym_html_attributes_repeat1] = aux_sym_html_attributes_repeat1,
  [alias_sym_ruby_code] = alias_sym_ruby_code,
  [alias_sym_self_close_slash] = alias_sym_self_close_slash,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_class_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_ruby_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__html_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_ruby_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__children] = {
    .visible = false,
    .named = true,
  },
  [sym__children_choice] = {
    .visible = false,
    .named = true,
  },
  [sym_html_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_output] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_run] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__children_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_ruby_code] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_self_close_slash] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_ruby_code,
  },
  [2] = {
    [1] = alias_sym_self_close_slash,
  },
  [3] = {
    [2] = alias_sym_self_close_slash,
  },
  [4] = {
    [3] = alias_sym_self_close_slash,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 10,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 15,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 16,
  [28] = 14,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 18,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 17,
  [40] = 19,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 13,
  [45] = 20,
  [46] = 46,
  [47] = 32,
  [48] = 42,
  [49] = 22,
  [50] = 26,
  [51] = 34,
  [52] = 29,
  [53] = 24,
  [54] = 37,
  [55] = 31,
  [56] = 33,
  [57] = 38,
  [58] = 25,
  [59] = 30,
  [60] = 36,
  [61] = 41,
  [62] = 43,
  [63] = 63,
  [64] = 63,
  [65] = 65,
  [66] = 65,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 68,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 73,
  [75] = 72,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 85,
  [91] = 89,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 93,
  [98] = 95,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 102,
  [105] = 101,
  [106] = 106,
  [107] = 106,
  [108] = 96,
  [109] = 99,
  [110] = 110,
  [111] = 110,
  [112] = 103,
  [113] = 113,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 27,
        '#', 35,
        '%', 12,
        '\'', 26,
        '(', 18,
        ')', 19,
        '-', 34,
        '.', 23,
        '/', 16,
        '=', 25,
        '{', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '%') ADVANCE(32);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '%') ADVANCE(12);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == '=') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\'') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == ')') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(36);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(14);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '%') ADVANCE(32);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_class_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '%') ADVANCE(32);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_ruby_expression);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__html_identifier);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 14, .external_lex_state = 2},
  [3] = {.lex_state = 14, .external_lex_state = 2},
  [4] = {.lex_state = 14, .external_lex_state = 2},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 4, .external_lex_state = 3},
  [10] = {.lex_state = 4, .external_lex_state = 3},
  [11] = {.lex_state = 4, .external_lex_state = 3},
  [12] = {.lex_state = 4, .external_lex_state = 3},
  [13] = {.lex_state = 14, .external_lex_state = 4},
  [14] = {.lex_state = 14, .external_lex_state = 4},
  [15] = {.lex_state = 14, .external_lex_state = 4},
  [16] = {.lex_state = 14, .external_lex_state = 4},
  [17] = {.lex_state = 14, .external_lex_state = 4},
  [18] = {.lex_state = 14, .external_lex_state = 4},
  [19] = {.lex_state = 14, .external_lex_state = 4},
  [20] = {.lex_state = 14, .external_lex_state = 5},
  [21] = {.lex_state = 4, .external_lex_state = 3},
  [22] = {.lex_state = 14, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 6},
  [24] = {.lex_state = 14, .external_lex_state = 2},
  [25] = {.lex_state = 14, .external_lex_state = 2},
  [26] = {.lex_state = 14, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 6},
  [28] = {.lex_state = 0, .external_lex_state = 6},
  [29] = {.lex_state = 14, .external_lex_state = 2},
  [30] = {.lex_state = 14, .external_lex_state = 2},
  [31] = {.lex_state = 14, .external_lex_state = 2},
  [32] = {.lex_state = 14, .external_lex_state = 2},
  [33] = {.lex_state = 14, .external_lex_state = 2},
  [34] = {.lex_state = 14, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 6},
  [36] = {.lex_state = 14, .external_lex_state = 2},
  [37] = {.lex_state = 14, .external_lex_state = 2},
  [38] = {.lex_state = 14, .external_lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 6},
  [40] = {.lex_state = 0, .external_lex_state = 6},
  [41] = {.lex_state = 14, .external_lex_state = 2},
  [42] = {.lex_state = 14, .external_lex_state = 2},
  [43] = {.lex_state = 14, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 6},
  [45] = {.lex_state = 0, .external_lex_state = 7},
  [46] = {.lex_state = 4, .external_lex_state = 3},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 4, .external_lex_state = 7},
  [64] = {.lex_state = 4, .external_lex_state = 7},
  [65] = {.lex_state = 4, .external_lex_state = 7},
  [66] = {.lex_state = 4, .external_lex_state = 7},
  [67] = {.lex_state = 4, .external_lex_state = 7},
  [68] = {.lex_state = 4, .external_lex_state = 7},
  [69] = {.lex_state = 4, .external_lex_state = 7},
  [70] = {.lex_state = 4, .external_lex_state = 7},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 4, .external_lex_state = 7},
  [73] = {.lex_state = 4, .external_lex_state = 7},
  [74] = {.lex_state = 4, .external_lex_state = 7},
  [75] = {.lex_state = 4, .external_lex_state = 7},
  [76] = {.lex_state = 7},
  [77] = {.lex_state = 7},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 4, .external_lex_state = 7},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 5},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 5},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 0, .external_lex_state = 6},
  [86] = {.lex_state = 6},
  [87] = {.lex_state = 6},
  [88] = {.lex_state = 7},
  [89] = {.lex_state = 2, .external_lex_state = 7},
  [90] = {.lex_state = 0, .external_lex_state = 6},
  [91] = {.lex_state = 2, .external_lex_state = 7},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 3},
  [102] = {.lex_state = 3},
  [103] = {.lex_state = 3},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 3},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 3},
  [108] = {.lex_state = 2},
  [109] = {.lex_state = 3},
  [110] = {.lex_state = 3},
  [111] = {.lex_state = 3},
  [112] = {.lex_state = 3},
  [113] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_ruby_expression] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym_ruby_attributes] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(94),
    [sym_tag] = STATE(7),
    [sym_comment] = STATE(7),
    [sym_class] = STATE(9),
    [sym_ruby_block_output] = STATE(7),
    [sym_ruby_block_run] = STATE(7),
    [sym_ruby_interpolation] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(5),
    [sym_id] = ACTIONS(7),
    [sym_name] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(19), 1,
      anon_sym_SLASH,
    ACTIONS(25), 1,
      anon_sym_DOT,
    ACTIONS(28), 1,
      anon_sym_EQ,
    ACTIONS(31), 1,
      sym_text_content,
    ACTIONS(34), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_POUND,
    STATE(11), 1,
      sym_class,
    ACTIONS(17), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(22), 2,
      sym_id,
      sym_name,
    STATE(2), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [39] = 11,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      anon_sym_SLASH,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(50), 1,
      sym_text_content,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(56), 1,
      sym__dedent,
    STATE(11), 1,
      sym_class,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(2), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [80] = 11,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      anon_sym_SLASH,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(50), 1,
      sym_text_content,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(58), 1,
      sym__dedent,
    STATE(11), 1,
      sym_class,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(2), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [121] = 9,
    ACTIONS(42), 1,
      anon_sym_SLASH,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(60), 1,
      sym_text_content,
    STATE(11), 1,
      sym_class,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(3), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [156] = 9,
    ACTIONS(42), 1,
      anon_sym_SLASH,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(62), 1,
      sym_text_content,
    STATE(11), 1,
      sym_class,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(4), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [191] = 9,
    ACTIONS(5), 1,
      anon_sym_SLASH,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_EQ,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_class,
    ACTIONS(7), 2,
      sym_id,
      sym_name,
    STATE(8), 6,
      sym_tag,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [225] = 9,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      anon_sym_SLASH,
    ACTIONS(74), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      anon_sym_EQ,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(83), 1,
      anon_sym_POUND,
    STATE(9), 1,
      sym_class,
    ACTIONS(71), 2,
      sym_id,
      sym_name,
    STATE(8), 6,
      sym_tag,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [259] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(86), 1,
      anon_sym_SLASH,
    ACTIONS(88), 1,
      anon_sym_SPACE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(96), 1,
      sym__newline,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    STATE(57), 1,
      sym_ruby_block_output,
    STATE(64), 1,
      sym_attributes,
    STATE(67), 1,
      sym_html_attributes,
    ACTIONS(92), 2,
      sym_id,
      sym_name,
    STATE(12), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [298] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_SPACE,
    ACTIONS(106), 1,
      sym__newline,
    STATE(32), 1,
      sym_ruby_block_output,
    STATE(65), 1,
      sym_attributes,
    STATE(67), 1,
      sym_html_attributes,
    ACTIONS(104), 2,
      sym_id,
      sym_name,
    STATE(21), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [337] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(108), 1,
      anon_sym_SLASH,
    ACTIONS(110), 1,
      anon_sym_SPACE,
    ACTIONS(114), 1,
      sym__newline,
    STATE(38), 1,
      sym_ruby_block_output,
    STATE(63), 1,
      sym_attributes,
    STATE(67), 1,
      sym_html_attributes,
    ACTIONS(112), 2,
      sym_id,
      sym_name,
    STATE(10), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [376] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    ACTIONS(118), 1,
      anon_sym_SPACE,
    ACTIONS(120), 1,
      sym__newline,
    STATE(47), 1,
      sym_ruby_block_output,
    STATE(66), 1,
      sym_attributes,
    STATE(67), 1,
      sym_html_attributes,
    ACTIONS(104), 2,
      sym_id,
      sym_name,
    STATE(21), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [415] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(25), 1,
      sym__children,
    ACTIONS(122), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(124), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [436] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(24), 1,
      sym__children,
    ACTIONS(128), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(130), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [457] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(26), 1,
      sym__children,
    ACTIONS(132), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(134), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [478] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(41), 1,
      sym__children,
    ACTIONS(136), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(138), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [499] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(32), 1,
      sym__children,
    ACTIONS(140), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(142), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [520] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(36), 1,
      sym__children,
    ACTIONS(144), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(146), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [541] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(31), 1,
      sym__children,
    ACTIONS(148), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(150), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [562] = 3,
    ACTIONS(156), 1,
      sym__newline,
    ACTIONS(152), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(154), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [580] = 5,
    ACTIONS(165), 1,
      anon_sym_DOT,
    ACTIONS(162), 2,
      sym_id,
      sym_name,
    STATE(21), 2,
      sym_class,
      aux_sym_tag_repeat1,
    ACTIONS(158), 3,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_EQ,
    ACTIONS(160), 3,
      sym__newline,
      sym_ruby_attributes,
      anon_sym_SPACE,
  [602] = 2,
    ACTIONS(168), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(170), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [617] = 4,
    ACTIONS(134), 1,
      anon_sym_POUND,
    ACTIONS(172), 1,
      sym__indent,
    STATE(50), 1,
      sym__children,
    ACTIONS(132), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [636] = 2,
    ACTIONS(174), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(176), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [651] = 2,
    ACTIONS(178), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(180), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [666] = 2,
    ACTIONS(136), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(138), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [681] = 4,
    ACTIONS(138), 1,
      anon_sym_POUND,
    ACTIONS(172), 1,
      sym__indent,
    STATE(61), 1,
      sym__children,
    ACTIONS(136), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [700] = 4,
    ACTIONS(130), 1,
      anon_sym_POUND,
    ACTIONS(172), 1,
      sym__indent,
    STATE(53), 1,
      sym__children,
    ACTIONS(128), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [719] = 2,
    ACTIONS(144), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(146), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [734] = 2,
    ACTIONS(128), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(130), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [749] = 2,
    ACTIONS(182), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(184), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [764] = 2,
    ACTIONS(132), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(134), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [779] = 2,
    ACTIONS(186), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(188), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [794] = 2,
    ACTIONS(190), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(192), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [809] = 4,
    ACTIONS(146), 1,
      anon_sym_POUND,
    ACTIONS(172), 1,
      sym__indent,
    STATE(60), 1,
      sym__children,
    ACTIONS(144), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [828] = 2,
    ACTIONS(194), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(196), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [843] = 2,
    ACTIONS(198), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(200), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [858] = 2,
    ACTIONS(140), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(142), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [873] = 4,
    ACTIONS(142), 1,
      anon_sym_POUND,
    ACTIONS(172), 1,
      sym__indent,
    STATE(47), 1,
      sym__children,
    ACTIONS(140), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [892] = 4,
    ACTIONS(150), 1,
      anon_sym_POUND,
    ACTIONS(172), 1,
      sym__indent,
    STATE(55), 1,
      sym__children,
    ACTIONS(148), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [911] = 2,
    ACTIONS(202), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(204), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [926] = 2,
    ACTIONS(122), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(124), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [941] = 2,
    ACTIONS(206), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(208), 8,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [956] = 4,
    ACTIONS(124), 1,
      anon_sym_POUND,
    ACTIONS(172), 1,
      sym__indent,
    STATE(58), 1,
      sym__children,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [975] = 3,
    ACTIONS(154), 1,
      anon_sym_POUND,
    ACTIONS(210), 1,
      sym__newline,
    ACTIONS(152), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [991] = 2,
    ACTIONS(214), 3,
      sym__newline,
      sym_ruby_attributes,
      anon_sym_SPACE,
    ACTIONS(212), 6,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
  [1005] = 2,
    ACTIONS(134), 1,
      anon_sym_POUND,
    ACTIONS(132), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1018] = 2,
    ACTIONS(124), 1,
      anon_sym_POUND,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1031] = 2,
    ACTIONS(170), 1,
      anon_sym_POUND,
    ACTIONS(168), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1044] = 2,
    ACTIONS(138), 1,
      anon_sym_POUND,
    ACTIONS(136), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1057] = 2,
    ACTIONS(192), 1,
      anon_sym_POUND,
    ACTIONS(190), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1070] = 2,
    ACTIONS(146), 1,
      anon_sym_POUND,
    ACTIONS(144), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1083] = 2,
    ACTIONS(176), 1,
      anon_sym_POUND,
    ACTIONS(174), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1096] = 2,
    ACTIONS(200), 1,
      anon_sym_POUND,
    ACTIONS(198), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1109] = 2,
    ACTIONS(184), 1,
      anon_sym_POUND,
    ACTIONS(182), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1122] = 2,
    ACTIONS(188), 1,
      anon_sym_POUND,
    ACTIONS(186), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1135] = 2,
    ACTIONS(142), 1,
      anon_sym_POUND,
    ACTIONS(140), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1148] = 2,
    ACTIONS(180), 1,
      anon_sym_POUND,
    ACTIONS(178), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1161] = 2,
    ACTIONS(130), 1,
      anon_sym_POUND,
    ACTIONS(128), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1174] = 2,
    ACTIONS(196), 1,
      anon_sym_POUND,
    ACTIONS(194), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1187] = 2,
    ACTIONS(204), 1,
      anon_sym_POUND,
    ACTIONS(202), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1200] = 2,
    ACTIONS(208), 1,
      anon_sym_POUND,
    ACTIONS(206), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
      anon_sym_DASH,
  [1213] = 5,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_SPACE,
    ACTIONS(106), 1,
      sym__newline,
    STATE(32), 1,
      sym_ruby_block_output,
  [1229] = 5,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    ACTIONS(118), 1,
      anon_sym_SPACE,
    ACTIONS(120), 1,
      sym__newline,
    STATE(47), 1,
      sym_ruby_block_output,
  [1245] = 5,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(216), 1,
      anon_sym_SLASH,
    ACTIONS(218), 1,
      anon_sym_SPACE,
    ACTIONS(220), 1,
      sym__newline,
    STATE(26), 1,
      sym_ruby_block_output,
  [1261] = 5,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(222), 1,
      anon_sym_SLASH,
    ACTIONS(224), 1,
      anon_sym_SPACE,
    ACTIONS(226), 1,
      sym__newline,
    STATE(50), 1,
      sym_ruby_block_output,
  [1277] = 2,
    ACTIONS(228), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(230), 2,
      sym__newline,
      anon_sym_SPACE,
  [1286] = 4,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(232), 1,
      anon_sym_SPACE,
    ACTIONS(234), 1,
      sym__newline,
    STATE(30), 1,
      sym_ruby_block_output,
  [1299] = 2,
    ACTIONS(236), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(238), 2,
      sym__newline,
      anon_sym_SPACE,
  [1308] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(240), 1,
      anon_sym_SPACE,
    ACTIONS(242), 1,
      sym__newline,
    STATE(59), 1,
      sym_ruby_block_output,
  [1321] = 4,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    ACTIONS(246), 1,
      sym_attribute_name,
    STATE(76), 1,
      aux_sym_html_attributes_repeat1,
    STATE(81), 1,
      sym_attribute,
  [1334] = 4,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(248), 1,
      anon_sym_SPACE,
    ACTIONS(250), 1,
      sym__newline,
    STATE(29), 1,
      sym_ruby_block_output,
  [1347] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(252), 1,
      anon_sym_SPACE,
    ACTIONS(254), 1,
      sym__newline,
    STATE(48), 1,
      sym_ruby_block_output,
  [1360] = 4,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(256), 1,
      anon_sym_SPACE,
    ACTIONS(258), 1,
      sym__newline,
    STATE(42), 1,
      sym_ruby_block_output,
  [1373] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(260), 1,
      anon_sym_SPACE,
    ACTIONS(262), 1,
      sym__newline,
    STATE(52), 1,
      sym_ruby_block_output,
  [1386] = 4,
    ACTIONS(246), 1,
      sym_attribute_name,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym_html_attributes_repeat1,
    STATE(81), 1,
      sym_attribute,
  [1399] = 4,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    ACTIONS(268), 1,
      sym_attribute_name,
    STATE(77), 1,
      aux_sym_html_attributes_repeat1,
    STATE(81), 1,
      sym_attribute,
  [1412] = 3,
    ACTIONS(271), 1,
      anon_sym_SPACE,
    ACTIONS(275), 1,
      anon_sym_EQ,
    ACTIONS(273), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1423] = 2,
    ACTIONS(277), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(279), 2,
      sym__newline,
      anon_sym_SPACE,
  [1432] = 2,
    ACTIONS(281), 1,
      anon_sym_SPACE,
    ACTIONS(283), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1440] = 2,
    ACTIONS(285), 1,
      anon_sym_SPACE,
    ACTIONS(287), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1448] = 3,
    ACTIONS(289), 1,
      anon_sym_SQUOTE,
    ACTIONS(291), 1,
      anon_sym_DQUOTE,
    STATE(84), 1,
      sym_quoted_attribute_value,
  [1458] = 2,
    ACTIONS(293), 1,
      anon_sym_SPACE,
    ACTIONS(295), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1466] = 2,
    ACTIONS(297), 1,
      anon_sym_SPACE,
    ACTIONS(299), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1474] = 2,
    ACTIONS(172), 1,
      sym__indent,
    STATE(49), 1,
      sym__children,
  [1481] = 2,
    ACTIONS(301), 1,
      anon_sym_SQUOTE,
    ACTIONS(303), 1,
      sym__html_identifier,
  [1488] = 2,
    ACTIONS(301), 1,
      anon_sym_DQUOTE,
    ACTIONS(305), 1,
      sym__html_identifier,
  [1495] = 1,
    ACTIONS(266), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1500] = 2,
    ACTIONS(307), 1,
      sym__text,
    ACTIONS(309), 1,
      sym__newline,
  [1507] = 2,
    ACTIONS(126), 1,
      sym__indent,
    STATE(22), 1,
      sym__children,
  [1514] = 2,
    ACTIONS(311), 1,
      sym__text,
    ACTIONS(313), 1,
      sym__newline,
  [1521] = 1,
    ACTIONS(315), 1,
      anon_sym_DQUOTE,
  [1525] = 1,
    ACTIONS(317), 1,
      sym__text,
  [1529] = 1,
    ACTIONS(319), 1,
      ts_builtin_sym_end,
  [1533] = 1,
    ACTIONS(321), 1,
      sym_ruby_expression,
  [1537] = 1,
    ACTIONS(323), 1,
      sym__text,
  [1541] = 1,
    ACTIONS(325), 1,
      sym__text,
  [1545] = 1,
    ACTIONS(327), 1,
      sym_ruby_expression,
  [1549] = 1,
    ACTIONS(329), 1,
      sym_text_content,
  [1553] = 1,
    ACTIONS(315), 1,
      anon_sym_SQUOTE,
  [1557] = 1,
    ACTIONS(331), 1,
      sym_text_content,
  [1561] = 1,
    ACTIONS(333), 1,
      sym_text_content,
  [1565] = 1,
    ACTIONS(335), 1,
      sym_text_content,
  [1569] = 1,
    ACTIONS(337), 1,
      sym_text_content,
  [1573] = 1,
    ACTIONS(339), 1,
      sym_text_content,
  [1577] = 1,
    ACTIONS(341), 1,
      sym_text_content,
  [1581] = 1,
    ACTIONS(343), 1,
      sym_text_content,
  [1585] = 1,
    ACTIONS(345), 1,
      sym__text,
  [1589] = 1,
    ACTIONS(347), 1,
      sym_text_content,
  [1593] = 1,
    ACTIONS(349), 1,
      sym_text_content,
  [1597] = 1,
    ACTIONS(351), 1,
      sym_text_content,
  [1601] = 1,
    ACTIONS(353), 1,
      sym_text_content,
  [1605] = 1,
    ACTIONS(355), 1,
      sym_class_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 121,
  [SMALL_STATE(6)] = 156,
  [SMALL_STATE(7)] = 191,
  [SMALL_STATE(8)] = 225,
  [SMALL_STATE(9)] = 259,
  [SMALL_STATE(10)] = 298,
  [SMALL_STATE(11)] = 337,
  [SMALL_STATE(12)] = 376,
  [SMALL_STATE(13)] = 415,
  [SMALL_STATE(14)] = 436,
  [SMALL_STATE(15)] = 457,
  [SMALL_STATE(16)] = 478,
  [SMALL_STATE(17)] = 499,
  [SMALL_STATE(18)] = 520,
  [SMALL_STATE(19)] = 541,
  [SMALL_STATE(20)] = 562,
  [SMALL_STATE(21)] = 580,
  [SMALL_STATE(22)] = 602,
  [SMALL_STATE(23)] = 617,
  [SMALL_STATE(24)] = 636,
  [SMALL_STATE(25)] = 651,
  [SMALL_STATE(26)] = 666,
  [SMALL_STATE(27)] = 681,
  [SMALL_STATE(28)] = 700,
  [SMALL_STATE(29)] = 719,
  [SMALL_STATE(30)] = 734,
  [SMALL_STATE(31)] = 749,
  [SMALL_STATE(32)] = 764,
  [SMALL_STATE(33)] = 779,
  [SMALL_STATE(34)] = 794,
  [SMALL_STATE(35)] = 809,
  [SMALL_STATE(36)] = 828,
  [SMALL_STATE(37)] = 843,
  [SMALL_STATE(38)] = 858,
  [SMALL_STATE(39)] = 873,
  [SMALL_STATE(40)] = 892,
  [SMALL_STATE(41)] = 911,
  [SMALL_STATE(42)] = 926,
  [SMALL_STATE(43)] = 941,
  [SMALL_STATE(44)] = 956,
  [SMALL_STATE(45)] = 975,
  [SMALL_STATE(46)] = 991,
  [SMALL_STATE(47)] = 1005,
  [SMALL_STATE(48)] = 1018,
  [SMALL_STATE(49)] = 1031,
  [SMALL_STATE(50)] = 1044,
  [SMALL_STATE(51)] = 1057,
  [SMALL_STATE(52)] = 1070,
  [SMALL_STATE(53)] = 1083,
  [SMALL_STATE(54)] = 1096,
  [SMALL_STATE(55)] = 1109,
  [SMALL_STATE(56)] = 1122,
  [SMALL_STATE(57)] = 1135,
  [SMALL_STATE(58)] = 1148,
  [SMALL_STATE(59)] = 1161,
  [SMALL_STATE(60)] = 1174,
  [SMALL_STATE(61)] = 1187,
  [SMALL_STATE(62)] = 1200,
  [SMALL_STATE(63)] = 1213,
  [SMALL_STATE(64)] = 1229,
  [SMALL_STATE(65)] = 1245,
  [SMALL_STATE(66)] = 1261,
  [SMALL_STATE(67)] = 1277,
  [SMALL_STATE(68)] = 1286,
  [SMALL_STATE(69)] = 1299,
  [SMALL_STATE(70)] = 1308,
  [SMALL_STATE(71)] = 1321,
  [SMALL_STATE(72)] = 1334,
  [SMALL_STATE(73)] = 1347,
  [SMALL_STATE(74)] = 1360,
  [SMALL_STATE(75)] = 1373,
  [SMALL_STATE(76)] = 1386,
  [SMALL_STATE(77)] = 1399,
  [SMALL_STATE(78)] = 1412,
  [SMALL_STATE(79)] = 1423,
  [SMALL_STATE(80)] = 1432,
  [SMALL_STATE(81)] = 1440,
  [SMALL_STATE(82)] = 1448,
  [SMALL_STATE(83)] = 1458,
  [SMALL_STATE(84)] = 1466,
  [SMALL_STATE(85)] = 1474,
  [SMALL_STATE(86)] = 1481,
  [SMALL_STATE(87)] = 1488,
  [SMALL_STATE(88)] = 1495,
  [SMALL_STATE(89)] = 1500,
  [SMALL_STATE(90)] = 1507,
  [SMALL_STATE(91)] = 1514,
  [SMALL_STATE(92)] = 1521,
  [SMALL_STATE(93)] = 1525,
  [SMALL_STATE(94)] = 1529,
  [SMALL_STATE(95)] = 1533,
  [SMALL_STATE(96)] = 1537,
  [SMALL_STATE(97)] = 1541,
  [SMALL_STATE(98)] = 1545,
  [SMALL_STATE(99)] = 1549,
  [SMALL_STATE(100)] = 1553,
  [SMALL_STATE(101)] = 1557,
  [SMALL_STATE(102)] = 1561,
  [SMALL_STATE(103)] = 1565,
  [SMALL_STATE(104)] = 1569,
  [SMALL_STATE(105)] = 1573,
  [SMALL_STATE(106)] = 1577,
  [SMALL_STATE(107)] = 1581,
  [SMALL_STATE(108)] = 1585,
  [SMALL_STATE(109)] = 1589,
  [SMALL_STATE(110)] = 1593,
  [SMALL_STATE(111)] = 1597,
  [SMALL_STATE(112)] = 1601,
  [SMALL_STATE(113)] = 1605,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 4),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 4),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 2),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 3),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 3, 0, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 3, 0, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 2, 0, 1),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 2, 0, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 2),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 4),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 4),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 4, 0, 1),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 4, 0, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__children, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 3),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 3),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 2, 0, 1),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 2, 0, 1),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 1, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0),
  [268] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [287] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_html_attributes_repeat1, 1, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [319] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token_ruby_attributes = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token_ruby_attributes] = sym_ruby_attributes,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [2] = {
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [4] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
  },
  [7] = {
    [ts_external_token__newline] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_haml_external_scanner_create(void);
void tree_sitter_haml_external_scanner_destroy(void *);
bool tree_sitter_haml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_haml_external_scanner_serialize(void *, char *);
void tree_sitter_haml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_haml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_haml_external_scanner_create,
      tree_sitter_haml_external_scanner_destroy,
      tree_sitter_haml_external_scanner_scan,
      tree_sitter_haml_external_scanner_serialize,
      tree_sitter_haml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
