#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 144
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 2
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  anon_sym_SLASH = 1,
  anon_sym_SPACE = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  sym_id = 5,
  sym_name = 6,
  sym_class_name = 7,
  anon_sym_DASH_POUND = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_DOT = 11,
  sym_attribute_name = 12,
  anon_sym_EQ = 13,
  anon_sym_SQUOTE = 14,
  anon_sym_DQUOTE = 15,
  sym__text = 16,
  sym__comment_content = 17,
  sym_text_content = 18,
  anon_sym_DASH = 19,
  anon_sym_POUND = 20,
  sym_ruby_expression = 21,
  sym__html_identifier = 22,
  sym__newline = 23,
  sym__indent = 24,
  sym__dedent = 25,
  sym_ruby_attributes = 26,
  sym_source_file = 27,
  sym_tag = 28,
  sym__children = 29,
  sym__children_choice = 30,
  sym_html_attributes = 31,
  sym_attributes = 32,
  sym_comment = 33,
  sym__comment_line = 34,
  sym__comment_block = 35,
  sym_comment_condition = 36,
  sym_class = 37,
  sym_attribute = 38,
  sym_quoted_attribute_value = 39,
  sym_ruby_block_output = 40,
  sym_ruby_block_run = 41,
  sym_ruby_interpolation = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_tag_repeat1 = 44,
  aux_sym__children_repeat1 = 45,
  aux_sym_html_attributes_repeat1 = 46,
  aux_sym__comment_line_repeat1 = 47,
  alias_sym_ruby_code = 48,
  alias_sym_self_close_slash = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH] = "/",
  [anon_sym_SPACE] = " ",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_id] = "id",
  [sym_name] = "name",
  [sym_class_name] = "class_name",
  [anon_sym_DASH_POUND] = "-#",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_EQ] = "=",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym__text] = "_text",
  [sym__comment_content] = "_comment_content",
  [sym_text_content] = "text_content",
  [anon_sym_DASH] = "-",
  [anon_sym_POUND] = "#",
  [sym_ruby_expression] = "ruby_expression",
  [sym__html_identifier] = "attribute_value",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_ruby_attributes] = "ruby_attributes",
  [sym_source_file] = "source_file",
  [sym_tag] = "tag",
  [sym__children] = "_children",
  [sym__children_choice] = "_children_choice",
  [sym_html_attributes] = "html_attributes",
  [sym_attributes] = "attributes",
  [sym_comment] = "comment",
  [sym__comment_line] = "_comment_line",
  [sym__comment_block] = "_comment_block",
  [sym_comment_condition] = "comment_condition",
  [sym_class] = "class",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_ruby_block_output] = "ruby_block_output",
  [sym_ruby_block_run] = "ruby_block_run",
  [sym_ruby_interpolation] = "ruby_interpolation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym__children_repeat1] = "_children_repeat1",
  [aux_sym_html_attributes_repeat1] = "html_attributes_repeat1",
  [aux_sym__comment_line_repeat1] = "_comment_line_repeat1",
  [alias_sym_ruby_code] = "ruby_code",
  [alias_sym_self_close_slash] = "self_close_slash",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_id] = sym_id,
  [sym_name] = sym_name,
  [sym_class_name] = sym_class_name,
  [anon_sym_DASH_POUND] = anon_sym_DASH_POUND,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__text] = sym__text,
  [sym__comment_content] = sym__comment_content,
  [sym_text_content] = sym_text_content,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_ruby_expression] = sym_ruby_expression,
  [sym__html_identifier] = sym__html_identifier,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_ruby_attributes] = sym_ruby_attributes,
  [sym_source_file] = sym_source_file,
  [sym_tag] = sym_tag,
  [sym__children] = sym__children,
  [sym__children_choice] = sym__children_choice,
  [sym_html_attributes] = sym_html_attributes,
  [sym_attributes] = sym_attributes,
  [sym_comment] = sym_comment,
  [sym__comment_line] = sym__comment_line,
  [sym__comment_block] = sym__comment_block,
  [sym_comment_condition] = sym_comment_condition,
  [sym_class] = sym_class,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_ruby_block_output] = sym_ruby_block_output,
  [sym_ruby_block_run] = sym_ruby_block_run,
  [sym_ruby_interpolation] = sym_ruby_interpolation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym__children_repeat1] = aux_sym__children_repeat1,
  [aux_sym_html_attributes_repeat1] = aux_sym_html_attributes_repeat1,
  [aux_sym__comment_line_repeat1] = aux_sym__comment_line_repeat1,
  [alias_sym_ruby_code] = alias_sym_ruby_code,
  [alias_sym_self_close_slash] = alias_sym_self_close_slash,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_class_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_content] = {
    .visible = false,
    .named = true,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_ruby_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__html_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_ruby_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__children] = {
    .visible = false,
    .named = true,
  },
  [sym__children_choice] = {
    .visible = false,
    .named = true,
  },
  [sym_html_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_line] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_block] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_output] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_run] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__children_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__comment_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_ruby_code] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_self_close_slash] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_ruby_code,
  },
  [2] = {
    [1] = alias_sym_self_close_slash,
  },
  [3] = {
    [2] = alias_sym_self_close_slash,
  },
  [4] = {
    [3] = alias_sym_self_close_slash,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 9,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 18,
  [23] = 19,
  [24] = 16,
  [25] = 25,
  [26] = 14,
  [27] = 15,
  [28] = 17,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 13,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 20,
  [49] = 21,
  [50] = 33,
  [51] = 46,
  [52] = 45,
  [53] = 39,
  [54] = 54,
  [55] = 47,
  [56] = 30,
  [57] = 29,
  [58] = 35,
  [59] = 31,
  [60] = 32,
  [61] = 36,
  [62] = 40,
  [63] = 38,
  [64] = 43,
  [65] = 41,
  [66] = 42,
  [67] = 44,
  [68] = 34,
  [69] = 69,
  [70] = 70,
  [71] = 69,
  [72] = 70,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 80,
  [82] = 82,
  [83] = 79,
  [84] = 82,
  [85] = 85,
  [86] = 86,
  [87] = 73,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 93,
  [97] = 94,
  [98] = 98,
  [99] = 90,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 100,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 105,
  [109] = 102,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 114,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 117,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 118,
  [127] = 125,
  [128] = 128,
  [129] = 119,
  [130] = 130,
  [131] = 131,
  [132] = 120,
  [133] = 133,
  [134] = 128,
  [135] = 123,
  [136] = 115,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 124,
  [141] = 133,
  [142] = 113,
  [143] = 131,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 31,
        '#', 42,
        '%', 12,
        '\'', 30,
        '(', 18,
        ')', 19,
        '-', 41,
        '.', 27,
        '/', 16,
        '=', 29,
        '[', 24,
        ']', 26,
        '{', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '%') ADVANCE(12);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == '=') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\'') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == ')') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(43);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(14);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_class_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH_POUND);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__comment_content);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__comment_content);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__comment_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '#') ADVANCE(23);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_ruby_expression);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__html_identifier);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 14, .external_lex_state = 2},
  [3] = {.lex_state = 14, .external_lex_state = 2},
  [4] = {.lex_state = 14, .external_lex_state = 2},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 4, .external_lex_state = 3},
  [10] = {.lex_state = 4, .external_lex_state = 3},
  [11] = {.lex_state = 4, .external_lex_state = 3},
  [12] = {.lex_state = 4, .external_lex_state = 3},
  [13] = {.lex_state = 14, .external_lex_state = 4},
  [14] = {.lex_state = 14, .external_lex_state = 4},
  [15] = {.lex_state = 14, .external_lex_state = 4},
  [16] = {.lex_state = 14, .external_lex_state = 4},
  [17] = {.lex_state = 14, .external_lex_state = 4},
  [18] = {.lex_state = 14, .external_lex_state = 4},
  [19] = {.lex_state = 14, .external_lex_state = 4},
  [20] = {.lex_state = 14, .external_lex_state = 5},
  [21] = {.lex_state = 14, .external_lex_state = 4},
  [22] = {.lex_state = 0, .external_lex_state = 6},
  [23] = {.lex_state = 0, .external_lex_state = 6},
  [24] = {.lex_state = 0, .external_lex_state = 6},
  [25] = {.lex_state = 4, .external_lex_state = 3},
  [26] = {.lex_state = 0, .external_lex_state = 6},
  [27] = {.lex_state = 0, .external_lex_state = 6},
  [28] = {.lex_state = 0, .external_lex_state = 6},
  [29] = {.lex_state = 14, .external_lex_state = 2},
  [30] = {.lex_state = 14, .external_lex_state = 2},
  [31] = {.lex_state = 14, .external_lex_state = 2},
  [32] = {.lex_state = 14, .external_lex_state = 2},
  [33] = {.lex_state = 14, .external_lex_state = 2},
  [34] = {.lex_state = 14, .external_lex_state = 2},
  [35] = {.lex_state = 14, .external_lex_state = 2},
  [36] = {.lex_state = 14, .external_lex_state = 2},
  [37] = {.lex_state = 0, .external_lex_state = 6},
  [38] = {.lex_state = 14, .external_lex_state = 2},
  [39] = {.lex_state = 14, .external_lex_state = 2},
  [40] = {.lex_state = 14, .external_lex_state = 2},
  [41] = {.lex_state = 14, .external_lex_state = 2},
  [42] = {.lex_state = 14, .external_lex_state = 2},
  [43] = {.lex_state = 14, .external_lex_state = 2},
  [44] = {.lex_state = 14, .external_lex_state = 2},
  [45] = {.lex_state = 14, .external_lex_state = 2},
  [46] = {.lex_state = 14, .external_lex_state = 2},
  [47] = {.lex_state = 14, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 7},
  [49] = {.lex_state = 0, .external_lex_state = 6},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 4, .external_lex_state = 3},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 4, .external_lex_state = 7},
  [70] = {.lex_state = 4, .external_lex_state = 7},
  [71] = {.lex_state = 4, .external_lex_state = 7},
  [72] = {.lex_state = 4, .external_lex_state = 7},
  [73] = {.lex_state = 4, .external_lex_state = 7},
  [74] = {.lex_state = 7},
  [75] = {.lex_state = 4, .external_lex_state = 7},
  [76] = {.lex_state = 7},
  [77] = {.lex_state = 4, .external_lex_state = 7},
  [78] = {.lex_state = 7},
  [79] = {.lex_state = 34, .external_lex_state = 7},
  [80] = {.lex_state = 4, .external_lex_state = 7},
  [81] = {.lex_state = 4, .external_lex_state = 7},
  [82] = {.lex_state = 4, .external_lex_state = 7},
  [83] = {.lex_state = 34, .external_lex_state = 7},
  [84] = {.lex_state = 4, .external_lex_state = 7},
  [85] = {.lex_state = 4, .external_lex_state = 7},
  [86] = {.lex_state = 5},
  [87] = {.lex_state = 4, .external_lex_state = 7},
  [88] = {.lex_state = 35, .external_lex_state = 2},
  [89] = {.lex_state = 5},
  [90] = {.lex_state = 35, .external_lex_state = 2},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 5},
  [93] = {.lex_state = 35, .external_lex_state = 2},
  [94] = {.lex_state = 35, .external_lex_state = 2},
  [95] = {.lex_state = 5},
  [96] = {.lex_state = 35, .external_lex_state = 2},
  [97] = {.lex_state = 35, .external_lex_state = 2},
  [98] = {.lex_state = 5},
  [99] = {.lex_state = 35, .external_lex_state = 2},
  [100] = {.lex_state = 35},
  [101] = {.lex_state = 6},
  [102] = {.lex_state = 35},
  [103] = {.lex_state = 35},
  [104] = {.lex_state = 7},
  [105] = {.lex_state = 35},
  [106] = {.lex_state = 35, .external_lex_state = 2},
  [107] = {.lex_state = 6},
  [108] = {.lex_state = 35},
  [109] = {.lex_state = 35},
  [110] = {.lex_state = 0, .external_lex_state = 7},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0, .external_lex_state = 7},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 2},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0, .external_lex_state = 7},
  [119] = {.lex_state = 3},
  [120] = {.lex_state = 3},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 3},
  [124] = {.lex_state = 0, .external_lex_state = 6},
  [125] = {.lex_state = 3},
  [126] = {.lex_state = 0, .external_lex_state = 7},
  [127] = {.lex_state = 3},
  [128] = {.lex_state = 3},
  [129] = {.lex_state = 3},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 3},
  [132] = {.lex_state = 3},
  [133] = {.lex_state = 0, .external_lex_state = 6},
  [134] = {.lex_state = 3},
  [135] = {.lex_state = 3},
  [136] = {.lex_state = 2},
  [137] = {.lex_state = 9},
  [138] = {.lex_state = 2},
  [139] = {.lex_state = 0, .external_lex_state = 7},
  [140] = {.lex_state = 0, .external_lex_state = 6},
  [141] = {.lex_state = 0, .external_lex_state = 6},
  [142] = {.lex_state = 0, .external_lex_state = 7},
  [143] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_DASH_POUND] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_ruby_expression] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym_ruby_attributes] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(122),
    [sym_tag] = STATE(8),
    [sym_comment] = STATE(8),
    [sym__comment_line] = STATE(57),
    [sym__comment_block] = STATE(57),
    [sym_class] = STATE(9),
    [sym_ruby_block_output] = STATE(8),
    [sym_ruby_block_run] = STATE(8),
    [sym_ruby_interpolation] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(5),
    [sym_id] = ACTIONS(7),
    [sym_name] = ACTIONS(7),
    [anon_sym_DASH_POUND] = ACTIONS(5),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(25), 1,
      anon_sym_DOT,
    ACTIONS(28), 1,
      anon_sym_EQ,
    ACTIONS(31), 1,
      sym_text_content,
    ACTIONS(34), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_POUND,
    STATE(12), 1,
      sym_class,
    ACTIONS(17), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(19), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(22), 2,
      sym_id,
      sym_name,
    STATE(29), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(2), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [44] = 12,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(50), 1,
      sym_text_content,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(56), 1,
      sym__dedent,
    STATE(12), 1,
      sym_class,
    ACTIONS(42), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(29), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(2), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [90] = 12,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(50), 1,
      sym_text_content,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(58), 1,
      sym__dedent,
    STATE(12), 1,
      sym_class,
    ACTIONS(42), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(29), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(2), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [136] = 10,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(60), 1,
      sym_text_content,
    STATE(12), 1,
      sym_class,
    ACTIONS(42), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(29), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(3), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [176] = 10,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(62), 1,
      sym_text_content,
    STATE(12), 1,
      sym_class,
    ACTIONS(42), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(29), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(4), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [216] = 10,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 1,
      anon_sym_DOT,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_POUND,
    STATE(9), 1,
      sym_class,
    ACTIONS(66), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(69), 2,
      sym_id,
      sym_name,
    STATE(57), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(7), 6,
      sym_tag,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [255] = 10,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_EQ,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_class,
    ACTIONS(5), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(7), 2,
      sym_id,
      sym_name,
    STATE(57), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(7), 6,
      sym_tag,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [294] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(86), 1,
      anon_sym_SLASH,
    ACTIONS(88), 1,
      anon_sym_SPACE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(96), 1,
      sym__newline,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    STATE(56), 1,
      sym_ruby_block_output,
    STATE(69), 1,
      sym_attributes,
    STATE(77), 1,
      sym_html_attributes,
    ACTIONS(92), 2,
      sym_id,
      sym_name,
    STATE(10), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [333] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_SPACE,
    ACTIONS(106), 1,
      sym__newline,
    STATE(50), 1,
      sym_ruby_block_output,
    STATE(70), 1,
      sym_attributes,
    STATE(77), 1,
      sym_html_attributes,
    ACTIONS(104), 2,
      sym_id,
      sym_name,
    STATE(25), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [372] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(108), 1,
      anon_sym_SLASH,
    ACTIONS(110), 1,
      anon_sym_SPACE,
    ACTIONS(112), 1,
      sym__newline,
    STATE(33), 1,
      sym_ruby_block_output,
    STATE(72), 1,
      sym_attributes,
    STATE(77), 1,
      sym_html_attributes,
    ACTIONS(104), 2,
      sym_id,
      sym_name,
    STATE(25), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [411] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_SPACE,
    ACTIONS(120), 1,
      sym__newline,
    STATE(30), 1,
      sym_ruby_block_output,
    STATE(71), 1,
      sym_attributes,
    STATE(77), 1,
      sym_html_attributes,
    ACTIONS(118), 2,
      sym_id,
      sym_name,
    STATE(11), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [450] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(33), 1,
      sym__children,
    ACTIONS(122), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(124), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [472] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(40), 1,
      sym__children,
    ACTIONS(128), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(130), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [494] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(43), 1,
      sym__children,
    ACTIONS(132), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(134), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [516] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(36), 1,
      sym__children,
    ACTIONS(136), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(138), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [538] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(44), 1,
      sym__children,
    ACTIONS(140), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(142), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [560] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(47), 1,
      sym__children,
    ACTIONS(144), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(146), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [582] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(35), 1,
      sym__children,
    ACTIONS(148), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(150), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [604] = 3,
    ACTIONS(156), 1,
      sym__newline,
    ACTIONS(152), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(154), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [623] = 3,
    ACTIONS(162), 1,
      sym__indent,
    ACTIONS(158), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(160), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [642] = 4,
    ACTIONS(164), 1,
      sym__indent,
    STATE(55), 1,
      sym__children,
    ACTIONS(146), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(144), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [662] = 4,
    ACTIONS(164), 1,
      sym__indent,
    STATE(58), 1,
      sym__children,
    ACTIONS(150), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(148), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [682] = 4,
    ACTIONS(164), 1,
      sym__indent,
    STATE(61), 1,
      sym__children,
    ACTIONS(138), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(136), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [702] = 5,
    ACTIONS(173), 1,
      anon_sym_DOT,
    ACTIONS(170), 2,
      sym_id,
      sym_name,
    STATE(25), 2,
      sym_class,
      aux_sym_tag_repeat1,
    ACTIONS(166), 3,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_EQ,
    ACTIONS(168), 3,
      sym__newline,
      sym_ruby_attributes,
      anon_sym_SPACE,
  [724] = 4,
    ACTIONS(164), 1,
      sym__indent,
    STATE(62), 1,
      sym__children,
    ACTIONS(130), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(128), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [744] = 4,
    ACTIONS(164), 1,
      sym__indent,
    STATE(64), 1,
      sym__children,
    ACTIONS(134), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(132), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [764] = 4,
    ACTIONS(164), 1,
      sym__indent,
    STATE(67), 1,
      sym__children,
    ACTIONS(142), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(140), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [784] = 2,
    ACTIONS(176), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(178), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [800] = 2,
    ACTIONS(122), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(124), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [816] = 2,
    ACTIONS(180), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(182), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [832] = 2,
    ACTIONS(184), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(186), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [848] = 2,
    ACTIONS(136), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(138), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [864] = 2,
    ACTIONS(148), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(150), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [880] = 2,
    ACTIONS(188), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(190), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [896] = 2,
    ACTIONS(140), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(142), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [912] = 4,
    ACTIONS(164), 1,
      sym__indent,
    STATE(50), 1,
      sym__children,
    ACTIONS(124), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [932] = 2,
    ACTIONS(132), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(134), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [948] = 2,
    ACTIONS(192), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(194), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [964] = 2,
    ACTIONS(196), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(198), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [980] = 2,
    ACTIONS(200), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(202), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [996] = 2,
    ACTIONS(204), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(206), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1012] = 2,
    ACTIONS(208), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(210), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1028] = 2,
    ACTIONS(212), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(214), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1044] = 2,
    ACTIONS(144), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(146), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1060] = 2,
    ACTIONS(216), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(218), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1076] = 2,
    ACTIONS(220), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(222), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1092] = 3,
    ACTIONS(224), 1,
      sym__newline,
    ACTIONS(154), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(152), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1109] = 3,
    ACTIONS(226), 1,
      sym__indent,
    ACTIONS(160), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(158), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1126] = 2,
    ACTIONS(138), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(136), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1140] = 2,
    ACTIONS(218), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(216), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1154] = 2,
    ACTIONS(146), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(144), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1168] = 2,
    ACTIONS(194), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(192), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1182] = 2,
    ACTIONS(230), 3,
      sym__newline,
      sym_ruby_attributes,
      anon_sym_SPACE,
    ACTIONS(228), 6,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
  [1196] = 2,
    ACTIONS(222), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(220), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1210] = 2,
    ACTIONS(124), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1224] = 2,
    ACTIONS(178), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(176), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1238] = 2,
    ACTIONS(190), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(188), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1252] = 2,
    ACTIONS(182), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(180), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1266] = 2,
    ACTIONS(186), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(184), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1280] = 2,
    ACTIONS(142), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(140), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1294] = 2,
    ACTIONS(198), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(196), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1308] = 2,
    ACTIONS(134), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(132), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1322] = 2,
    ACTIONS(210), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(208), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1336] = 2,
    ACTIONS(202), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(200), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1350] = 2,
    ACTIONS(206), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(204), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1364] = 2,
    ACTIONS(214), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(212), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1378] = 2,
    ACTIONS(150), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(148), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1392] = 5,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_SPACE,
    ACTIONS(106), 1,
      sym__newline,
    STATE(50), 1,
      sym_ruby_block_output,
  [1408] = 5,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(232), 1,
      anon_sym_SLASH,
    ACTIONS(234), 1,
      anon_sym_SPACE,
    ACTIONS(236), 1,
      sym__newline,
    STATE(61), 1,
      sym_ruby_block_output,
  [1424] = 5,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(108), 1,
      anon_sym_SLASH,
    ACTIONS(110), 1,
      anon_sym_SPACE,
    ACTIONS(112), 1,
      sym__newline,
    STATE(33), 1,
      sym_ruby_block_output,
  [1440] = 5,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(238), 1,
      anon_sym_SLASH,
    ACTIONS(240), 1,
      anon_sym_SPACE,
    ACTIONS(242), 1,
      sym__newline,
    STATE(36), 1,
      sym_ruby_block_output,
  [1456] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(244), 1,
      anon_sym_SPACE,
    ACTIONS(246), 1,
      sym__newline,
    STATE(52), 1,
      sym_ruby_block_output,
  [1469] = 4,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    ACTIONS(250), 1,
      sym_attribute_name,
    STATE(78), 1,
      aux_sym_html_attributes_repeat1,
    STATE(89), 1,
      sym_attribute,
  [1482] = 2,
    ACTIONS(252), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(254), 2,
      sym__newline,
      anon_sym_SPACE,
  [1491] = 4,
    ACTIONS(250), 1,
      sym_attribute_name,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_html_attributes_repeat1,
    STATE(89), 1,
      sym_attribute,
  [1504] = 2,
    ACTIONS(258), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(260), 2,
      sym__newline,
      anon_sym_SPACE,
  [1513] = 4,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    ACTIONS(264), 1,
      sym_attribute_name,
    STATE(78), 1,
      aux_sym_html_attributes_repeat1,
    STATE(89), 1,
      sym_attribute,
  [1526] = 4,
    ACTIONS(267), 1,
      anon_sym_LBRACK,
    ACTIONS(269), 1,
      sym__comment_content,
    ACTIONS(271), 1,
      sym__newline,
    STATE(113), 1,
      sym_comment_condition,
  [1539] = 4,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(273), 1,
      anon_sym_SPACE,
    ACTIONS(275), 1,
      sym__newline,
    STATE(34), 1,
      sym_ruby_block_output,
  [1552] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(277), 1,
      anon_sym_SPACE,
    ACTIONS(279), 1,
      sym__newline,
    STATE(68), 1,
      sym_ruby_block_output,
  [1565] = 4,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(281), 1,
      anon_sym_SPACE,
    ACTIONS(283), 1,
      sym__newline,
    STATE(38), 1,
      sym_ruby_block_output,
  [1578] = 4,
    ACTIONS(267), 1,
      anon_sym_LBRACK,
    ACTIONS(285), 1,
      sym__comment_content,
    ACTIONS(287), 1,
      sym__newline,
    STATE(142), 1,
      sym_comment_condition,
  [1591] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(289), 1,
      anon_sym_SPACE,
    ACTIONS(291), 1,
      sym__newline,
    STATE(63), 1,
      sym_ruby_block_output,
  [1604] = 2,
    ACTIONS(293), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(295), 2,
      sym__newline,
      anon_sym_SPACE,
  [1613] = 3,
    ACTIONS(297), 1,
      anon_sym_SPACE,
    ACTIONS(301), 1,
      anon_sym_EQ,
    ACTIONS(299), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1624] = 4,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(303), 1,
      anon_sym_SPACE,
    ACTIONS(305), 1,
      sym__newline,
    STATE(45), 1,
      sym_ruby_block_output,
  [1637] = 3,
    ACTIONS(307), 1,
      sym__comment_content,
    ACTIONS(310), 1,
      sym__dedent,
    STATE(88), 1,
      aux_sym__comment_line_repeat1,
  [1647] = 2,
    ACTIONS(312), 1,
      anon_sym_SPACE,
    ACTIONS(314), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1655] = 3,
    ACTIONS(316), 1,
      sym__comment_content,
    ACTIONS(318), 1,
      sym__dedent,
    STATE(88), 1,
      aux_sym__comment_line_repeat1,
  [1665] = 3,
    ACTIONS(320), 1,
      anon_sym_SQUOTE,
    ACTIONS(322), 1,
      anon_sym_DQUOTE,
    STATE(92), 1,
      sym_quoted_attribute_value,
  [1675] = 2,
    ACTIONS(324), 1,
      anon_sym_SPACE,
    ACTIONS(326), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1683] = 3,
    ACTIONS(316), 1,
      sym__comment_content,
    ACTIONS(328), 1,
      sym__dedent,
    STATE(88), 1,
      aux_sym__comment_line_repeat1,
  [1693] = 3,
    ACTIONS(316), 1,
      sym__comment_content,
    ACTIONS(330), 1,
      sym__dedent,
    STATE(88), 1,
      aux_sym__comment_line_repeat1,
  [1703] = 2,
    ACTIONS(332), 1,
      anon_sym_SPACE,
    ACTIONS(334), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1711] = 3,
    ACTIONS(316), 1,
      sym__comment_content,
    ACTIONS(336), 1,
      sym__dedent,
    STATE(88), 1,
      aux_sym__comment_line_repeat1,
  [1721] = 3,
    ACTIONS(316), 1,
      sym__comment_content,
    ACTIONS(338), 1,
      sym__dedent,
    STATE(88), 1,
      aux_sym__comment_line_repeat1,
  [1731] = 2,
    ACTIONS(340), 1,
      anon_sym_SPACE,
    ACTIONS(342), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1739] = 3,
    ACTIONS(316), 1,
      sym__comment_content,
    ACTIONS(344), 1,
      sym__dedent,
    STATE(88), 1,
      aux_sym__comment_line_repeat1,
  [1749] = 2,
    ACTIONS(316), 1,
      sym__comment_content,
    STATE(96), 1,
      aux_sym__comment_line_repeat1,
  [1756] = 2,
    ACTIONS(346), 1,
      anon_sym_DQUOTE,
    ACTIONS(348), 1,
      sym__html_identifier,
  [1763] = 2,
    ACTIONS(316), 1,
      sym__comment_content,
    STATE(94), 1,
      aux_sym__comment_line_repeat1,
  [1770] = 2,
    ACTIONS(316), 1,
      sym__comment_content,
    STATE(93), 1,
      aux_sym__comment_line_repeat1,
  [1777] = 1,
    ACTIONS(262), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1782] = 2,
    ACTIONS(316), 1,
      sym__comment_content,
    STATE(90), 1,
      aux_sym__comment_line_repeat1,
  [1789] = 1,
    ACTIONS(310), 2,
      sym__dedent,
      sym__comment_content,
  [1794] = 2,
    ACTIONS(346), 1,
      anon_sym_SQUOTE,
    ACTIONS(350), 1,
      sym__html_identifier,
  [1801] = 2,
    ACTIONS(316), 1,
      sym__comment_content,
    STATE(99), 1,
      aux_sym__comment_line_repeat1,
  [1808] = 2,
    ACTIONS(316), 1,
      sym__comment_content,
    STATE(97), 1,
      aux_sym__comment_line_repeat1,
  [1815] = 1,
    ACTIONS(352), 1,
      sym__newline,
  [1819] = 1,
    ACTIONS(354), 1,
      anon_sym_SQUOTE,
  [1823] = 1,
    ACTIONS(354), 1,
      anon_sym_DQUOTE,
  [1827] = 1,
    ACTIONS(356), 1,
      sym__newline,
  [1831] = 1,
    ACTIONS(358), 1,
      sym__text,
  [1835] = 1,
    ACTIONS(360), 1,
      sym__text,
  [1839] = 1,
    ACTIONS(362), 1,
      sym__text,
  [1843] = 1,
    ACTIONS(364), 1,
      sym_ruby_expression,
  [1847] = 1,
    ACTIONS(366), 1,
      sym__newline,
  [1851] = 1,
    ACTIONS(368), 1,
      sym_text_content,
  [1855] = 1,
    ACTIONS(370), 1,
      sym_text_content,
  [1859] = 1,
    ACTIONS(372), 1,
      sym_ruby_expression,
  [1863] = 1,
    ACTIONS(374), 1,
      ts_builtin_sym_end,
  [1867] = 1,
    ACTIONS(376), 1,
      sym_text_content,
  [1871] = 1,
    ACTIONS(378), 1,
      sym__indent,
  [1875] = 1,
    ACTIONS(380), 1,
      sym_text_content,
  [1879] = 1,
    ACTIONS(382), 1,
      sym__newline,
  [1883] = 1,
    ACTIONS(384), 1,
      sym_text_content,
  [1887] = 1,
    ACTIONS(386), 1,
      sym_text_content,
  [1891] = 1,
    ACTIONS(388), 1,
      sym_text_content,
  [1895] = 1,
    ACTIONS(390), 1,
      anon_sym_RBRACK,
  [1899] = 1,
    ACTIONS(392), 1,
      sym_text_content,
  [1903] = 1,
    ACTIONS(394), 1,
      sym_text_content,
  [1907] = 1,
    ACTIONS(396), 1,
      sym__indent,
  [1911] = 1,
    ACTIONS(398), 1,
      sym_text_content,
  [1915] = 1,
    ACTIONS(400), 1,
      sym_text_content,
  [1919] = 1,
    ACTIONS(402), 1,
      sym__text,
  [1923] = 1,
    ACTIONS(404), 1,
      sym_class_name,
  [1927] = 1,
    ACTIONS(406), 1,
      sym__text,
  [1931] = 1,
    ACTIONS(408), 1,
      sym__newline,
  [1935] = 1,
    ACTIONS(410), 1,
      sym__indent,
  [1939] = 1,
    ACTIONS(412), 1,
      sym__indent,
  [1943] = 1,
    ACTIONS(414), 1,
      sym__newline,
  [1947] = 1,
    ACTIONS(416), 1,
      sym_text_content,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 136,
  [SMALL_STATE(6)] = 176,
  [SMALL_STATE(7)] = 216,
  [SMALL_STATE(8)] = 255,
  [SMALL_STATE(9)] = 294,
  [SMALL_STATE(10)] = 333,
  [SMALL_STATE(11)] = 372,
  [SMALL_STATE(12)] = 411,
  [SMALL_STATE(13)] = 450,
  [SMALL_STATE(14)] = 472,
  [SMALL_STATE(15)] = 494,
  [SMALL_STATE(16)] = 516,
  [SMALL_STATE(17)] = 538,
  [SMALL_STATE(18)] = 560,
  [SMALL_STATE(19)] = 582,
  [SMALL_STATE(20)] = 604,
  [SMALL_STATE(21)] = 623,
  [SMALL_STATE(22)] = 642,
  [SMALL_STATE(23)] = 662,
  [SMALL_STATE(24)] = 682,
  [SMALL_STATE(25)] = 702,
  [SMALL_STATE(26)] = 724,
  [SMALL_STATE(27)] = 744,
  [SMALL_STATE(28)] = 764,
  [SMALL_STATE(29)] = 784,
  [SMALL_STATE(30)] = 800,
  [SMALL_STATE(31)] = 816,
  [SMALL_STATE(32)] = 832,
  [SMALL_STATE(33)] = 848,
  [SMALL_STATE(34)] = 864,
  [SMALL_STATE(35)] = 880,
  [SMALL_STATE(36)] = 896,
  [SMALL_STATE(37)] = 912,
  [SMALL_STATE(38)] = 932,
  [SMALL_STATE(39)] = 948,
  [SMALL_STATE(40)] = 964,
  [SMALL_STATE(41)] = 980,
  [SMALL_STATE(42)] = 996,
  [SMALL_STATE(43)] = 1012,
  [SMALL_STATE(44)] = 1028,
  [SMALL_STATE(45)] = 1044,
  [SMALL_STATE(46)] = 1060,
  [SMALL_STATE(47)] = 1076,
  [SMALL_STATE(48)] = 1092,
  [SMALL_STATE(49)] = 1109,
  [SMALL_STATE(50)] = 1126,
  [SMALL_STATE(51)] = 1140,
  [SMALL_STATE(52)] = 1154,
  [SMALL_STATE(53)] = 1168,
  [SMALL_STATE(54)] = 1182,
  [SMALL_STATE(55)] = 1196,
  [SMALL_STATE(56)] = 1210,
  [SMALL_STATE(57)] = 1224,
  [SMALL_STATE(58)] = 1238,
  [SMALL_STATE(59)] = 1252,
  [SMALL_STATE(60)] = 1266,
  [SMALL_STATE(61)] = 1280,
  [SMALL_STATE(62)] = 1294,
  [SMALL_STATE(63)] = 1308,
  [SMALL_STATE(64)] = 1322,
  [SMALL_STATE(65)] = 1336,
  [SMALL_STATE(66)] = 1350,
  [SMALL_STATE(67)] = 1364,
  [SMALL_STATE(68)] = 1378,
  [SMALL_STATE(69)] = 1392,
  [SMALL_STATE(70)] = 1408,
  [SMALL_STATE(71)] = 1424,
  [SMALL_STATE(72)] = 1440,
  [SMALL_STATE(73)] = 1456,
  [SMALL_STATE(74)] = 1469,
  [SMALL_STATE(75)] = 1482,
  [SMALL_STATE(76)] = 1491,
  [SMALL_STATE(77)] = 1504,
  [SMALL_STATE(78)] = 1513,
  [SMALL_STATE(79)] = 1526,
  [SMALL_STATE(80)] = 1539,
  [SMALL_STATE(81)] = 1552,
  [SMALL_STATE(82)] = 1565,
  [SMALL_STATE(83)] = 1578,
  [SMALL_STATE(84)] = 1591,
  [SMALL_STATE(85)] = 1604,
  [SMALL_STATE(86)] = 1613,
  [SMALL_STATE(87)] = 1624,
  [SMALL_STATE(88)] = 1637,
  [SMALL_STATE(89)] = 1647,
  [SMALL_STATE(90)] = 1655,
  [SMALL_STATE(91)] = 1665,
  [SMALL_STATE(92)] = 1675,
  [SMALL_STATE(93)] = 1683,
  [SMALL_STATE(94)] = 1693,
  [SMALL_STATE(95)] = 1703,
  [SMALL_STATE(96)] = 1711,
  [SMALL_STATE(97)] = 1721,
  [SMALL_STATE(98)] = 1731,
  [SMALL_STATE(99)] = 1739,
  [SMALL_STATE(100)] = 1749,
  [SMALL_STATE(101)] = 1756,
  [SMALL_STATE(102)] = 1763,
  [SMALL_STATE(103)] = 1770,
  [SMALL_STATE(104)] = 1777,
  [SMALL_STATE(105)] = 1782,
  [SMALL_STATE(106)] = 1789,
  [SMALL_STATE(107)] = 1794,
  [SMALL_STATE(108)] = 1801,
  [SMALL_STATE(109)] = 1808,
  [SMALL_STATE(110)] = 1815,
  [SMALL_STATE(111)] = 1819,
  [SMALL_STATE(112)] = 1823,
  [SMALL_STATE(113)] = 1827,
  [SMALL_STATE(114)] = 1831,
  [SMALL_STATE(115)] = 1835,
  [SMALL_STATE(116)] = 1839,
  [SMALL_STATE(117)] = 1843,
  [SMALL_STATE(118)] = 1847,
  [SMALL_STATE(119)] = 1851,
  [SMALL_STATE(120)] = 1855,
  [SMALL_STATE(121)] = 1859,
  [SMALL_STATE(122)] = 1863,
  [SMALL_STATE(123)] = 1867,
  [SMALL_STATE(124)] = 1871,
  [SMALL_STATE(125)] = 1875,
  [SMALL_STATE(126)] = 1879,
  [SMALL_STATE(127)] = 1883,
  [SMALL_STATE(128)] = 1887,
  [SMALL_STATE(129)] = 1891,
  [SMALL_STATE(130)] = 1895,
  [SMALL_STATE(131)] = 1899,
  [SMALL_STATE(132)] = 1903,
  [SMALL_STATE(133)] = 1907,
  [SMALL_STATE(134)] = 1911,
  [SMALL_STATE(135)] = 1915,
  [SMALL_STATE(136)] = 1919,
  [SMALL_STATE(137)] = 1923,
  [SMALL_STATE(138)] = 1927,
  [SMALL_STATE(139)] = 1931,
  [SMALL_STATE(140)] = 1935,
  [SMALL_STATE(141)] = 1939,
  [SMALL_STATE(142)] = 1943,
  [SMALL_STATE(143)] = 1947,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(137),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(137),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(137),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(136),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(114),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(136),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 3, 0, 1),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 3, 0, 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 3),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 3),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 4),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 4),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 2),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 2, 0, 1),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 2, 0, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_line, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comment_line, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [173] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(137),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 2, 0, 1),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 2, 0, 1),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 2),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 2),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_line, 6, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comment_line, 6, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 4, 0, 1),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 4, 0, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_block, 5, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comment_block, 5, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__children, 3, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 3),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 3),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_block, 6, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comment_block, 6, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 4),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 4),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 1, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 1, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0),
  [264] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(138),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [307] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__comment_line_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__comment_line_repeat1, 2, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_html_attributes_repeat1, 1, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 0),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [334] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [342] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [374] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [408] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_condition, 3, 0, 0),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token_ruby_attributes = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token_ruby_attributes] = sym_ruby_attributes,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [2] = {
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [4] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
  },
  [7] = {
    [ts_external_token__newline] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_haml_external_scanner_create(void);
void tree_sitter_haml_external_scanner_destroy(void *);
bool tree_sitter_haml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_haml_external_scanner_serialize(void *, char *);
void tree_sitter_haml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_haml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_haml_external_scanner_create,
      tree_sitter_haml_external_scanner_destroy,
      tree_sitter_haml_external_scanner_scan,
      tree_sitter_haml_external_scanner_serialize,
      tree_sitter_haml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
